/* Generated by           cobc 2.0.0 */
/* Generated from         cisp-error.cbl */
/* Generated at           Apr 27 2017 17:51:28 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\cisp-error.dll -std=default -Wall -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin cisp-error.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {11, (cob_u8_ptr)"THROW-ERROR", &a_1};
static const cob_field c_2	= {10, (cob_u8_ptr)"CISP-ERROR", &a_1};
static const cob_field c_3	= {1, (cob_u8_ptr)":", &a_1};
static const cob_field c_4	= {6, (cob_u8_ptr)"Fatal:", &a_1};
static const cob_field c_5	= {10, (cob_u8_ptr)"RECURSION:", &a_1};
static const cob_field c_6	= {1, (cob_u8_ptr)"Y", &a_1};
static const cob_field c_7	= {5, (cob_u8_ptr)"CLOSE", &a_1};


/* Strings */
static const char st_1[]	= "cisp-error.cbl";
static const char st_2[]	= "MAIN-PROCEDURE";
static const char st_3[]	= "EVALUATE";
static const char st_4[]	= "PERFORM";
static const char st_5[]	= "THROW-ERROR-PROCEDURE";
static const char st_6[]	= "DISPLAY";
static const char st_7[]	= "IF";
static const char st_8[]	= "END-CISP-PROCEDURE";
static const char st_9[]	= "STOP RUN";
static const char st_10[]	= "LOG-ERROR-PROCEDURE";
static const char st_11[]	= "MOVE";
static const char st_12[]	= "STRING";
static const char st_13[]	= "CALL";
static const char st_14[]	= "CLOSE-OPEN-FILES-PROCEDURE";

