/* Generated by           cobc 2.0.0 */
/* Generated from         cisp.cbl */
/* Generated at           Apr 24 2017 18:33:42 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\cisp.exe -std=default -Wall -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin cisp.cbl */

/* Program local variables for 'CISP' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File TESTS-FILE */
static cob_file		*h_TESTS_FILE = NULL;
static unsigned char	h_TESTS_FILE_status[4];

/* Call pointers */
static cob_call_union	call_LOGGER;
static cob_call_union	call_TOKENIZER;
static cob_call_union	call_LISP;

/* Call parameters */
cob_field		*cob_procedure_params[3];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_7[30] __attribute__((aligned));	/* TESTS-FILE Record */
static cob_u8_t	b_8[104] __attribute__((aligned));	/* WS-CMD-LINE */
static cob_u8_t	b_11[5] __attribute__((aligned));	/* WS-LOG-OPERATION-FLAG */
static cob_u8_t	b_12[140] __attribute__((aligned));	/* WS-LOG-RECORD */
static cob_u8_t	b_15[30] __attribute__((aligned));	/* WS-LISP-FILE-NAME */
static cob_u8_t	b_17[5204] __attribute__((aligned));	/* WS-LISP-SYMBOLS */

/* End of data storage */


/* Fields */
static cob_field f_7	= {30, b_7, &a_2};	/* TESTS-FILE Record */
static cob_field f_9	= {100, b_8, &a_2};	/* WS-CMD-LINE-VAL */
static cob_field f_10	= {4, b_8 + 100, &a_1};	/* WS-CMD-LINE-NUM-AGRS */
static cob_field f_11	= {5, b_11, &a_2};	/* WS-LOG-OPERATION-FLAG */
static cob_field f_12	= {140, b_12, &a_3};	/* WS-LOG-RECORD */
static cob_field f_13	= {40, b_12, &a_2};	/* WS-LOG-RECORD-FUNCTION-NAME */
static cob_field f_14	= {100, b_12 + 40, &a_2};	/* WS-LOG-RECORD-MESSAGE */
static cob_field f_15	= {30, b_15, &a_2};	/* WS-LISP-FILE-NAME */
static cob_field f_17	= {5204, b_17, &a_3};	/* WS-LISP-SYMBOLS */

/* End of fields */

