/* Generated by           cobc 2.0.0 */
/* Generated from         cisp.cbl */
/* Generated at           Apr 22 2017 21:11:21 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\cisp.exe -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin cisp.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"cisp.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 22 2017 21:11:21"
#define  COB_MODULE_DATE		20170422
#define  COB_MODULE_TIME		211121

/* Global variables */
#include "cisp.c.h"

/* Function prototypes */

static int		CISP ();
static int		CISP_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CISP ());
}

/* Functions */

/* PROGRAM-ID 'CISP' */

/* ENTRY 'CISP' */

static int
CISP ()
{
  return CISP_ (0);
}

static int
CISP_ (const int entry)
{
  /* Program local variables */
  #include "cisp.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 35        : Entry     CISP                    : cisp.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 35);
  cob_trace_section (st_3, st_1, 35);

  /* Line: 35        : Paragraph MAIN-PROCEDURE          : cisp.cbl */
  cob_trace_section (st_4, st_1, 35);

  /* Line: 36        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 36, NULL, st_5, st_6);
  memcpy (b_6, "OPEN ", 5);

  /* Line: 37        : CALL               : cisp.cbl */
  cob_set_location (st_1, 37, NULL, st_5, st_7);
  cob_procedure_params[0] = &f_6;
  cob_procedure_params[1] = &f_7;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_6, b_7);

  /* Line: 39        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 39, NULL, st_5, st_6);
  memcpy (b_6, "ADD  ", 5);

  /* Line: 40        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 40, NULL, st_5, st_6);
  cob_move ((cob_field *)&c_1, &f_8);

  /* Line: 41        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 41, NULL, st_5, st_6);
  cob_move ((cob_field *)&c_2, &f_9);

  /* Line: 42        : CALL               : cisp.cbl */
  cob_set_location (st_1, 42, NULL, st_5, st_7);
  cob_procedure_params[0] = &f_6;
  cob_procedure_params[1] = &f_7;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_6, b_7);

  /* Line: 43        : CALL               : cisp.cbl */
  cob_set_location (st_1, 43, NULL, st_5, st_7);
  {
    cob_content	content_1;
    cob_field	content_fb_1 = { 4, content_1.data, &a_3 };

    content_1.dataint = 100;
    cob_procedure_params[0] = &content_fb_1;
    cob_procedure_params[1] = &f_11;
    cob_glob_ptr->cob_call_params = 2;
    if (unlikely(call_TOKENIZER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
      call_TOKENIZER.funcvoid = cob_resolve_cobol ("TOKENIZER", 0, 1);
    }
    b_1 = ((int (*)(void *, void *))call_TOKENIZER.funcint) (content_1.data, b_11);
  }

  /* Line: 45        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 45, NULL, st_5, st_6);
  memcpy (b_6, "ADD  ", 5);

  /* Line: 46        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 46, NULL, st_5, st_6);
  cob_move ((cob_field *)&c_3, &f_8);

  /* Line: 47        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 47, NULL, st_5, st_6);
  cob_move ((cob_field *)&c_4, &f_9);

  /* Line: 48        : CALL               : cisp.cbl */
  cob_set_location (st_1, 48, NULL, st_5, st_7);
  cob_procedure_params[0] = &f_6;
  cob_procedure_params[1] = &f_7;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_6, b_7);

  /* Line: 49        : CALL               : cisp.cbl */
  cob_set_location (st_1, 49, NULL, st_5, st_7);
  cob_procedure_params[0] = &f_11;
  cob_glob_ptr->cob_call_params = 1;
  if (unlikely(call_LISP.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LISP.funcvoid = cob_resolve_cobol ("LISP", 0, 1);
  }
  b_1 = ((int (*)(void *))call_LISP.funcint) (b_11);

  /* Line: 50        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 50, NULL, st_5, st_6);
  memcpy (b_6, "CLOSE", 5);

  /* Line: 51        : CALL               : cisp.cbl */
  cob_set_location (st_1, 51, NULL, st_5, st_7);
  cob_procedure_params[0] = &f_6;
  cob_procedure_params[1] = &f_7;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_6, b_7);

  /* Line: 52        : GOBACK             : cisp.cbl */
  cob_set_location (st_1, 52, NULL, st_5, st_8);
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_9, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "CISP";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())CISP;
  module->module_cancel.funcptr = (void *(*)())CISP_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_6, 32, 5);
  memset (b_7, 32, 140);
  memset (b_11, 48, 4);
  memset (b_11 + 4 + 50 * 0, 32, 5000);
  memset (b_11 + 5004 + 2 * 0, 48, 200);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'CISP' */

/* End functions */

