/* Generated by           cobc 2.0.0 */
/* Generated from         cisp.cbl */
/* Generated at           Apr 23 2017 01:35:23 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\cisp.exe -std=default -Wall -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin cisp.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x11,   9,   0, 0x0041, NULL};


/* Constants */
static const cob_field c_1	= {5, (cob_u8_ptr)"FILE:", &a_1};
static const cob_field c_2	= {9, (cob_u8_ptr)"TOKENIZER", &a_1};
static const cob_field c_3	= {18, (cob_u8_ptr)"Starting Tokenizer", &a_1};
static const cob_field c_4	= {4, (cob_u8_ptr)"LISP", &a_1};
static const cob_field c_5	= {25, (cob_u8_ptr)"Starting Lisp Evalutation", &a_1};
static const cob_field c_6	= {23, (cob_u8_ptr)"..\\test\\tests-lists.txt", &a_1};


/* Strings */
static const char st_1[]	= "cisp.cbl";
static const char st_2[]	= "MAIN-PROCEDURE";
static const char st_3[]	= "PERFORM";
static const char st_4[]	= "OPEN";
static const char st_5[]	= "MOVE";
static const char st_6[]	= "READ";
static const char st_7[]	= "CLOSE";
static const char st_8[]	= "GOBACK";
static const char st_9[]	= "LISP-PROCEDURE";
static const char st_10[]	= "DISPLAY";
static const char st_11[]	= "TOKENIZE-LISP-PROCEDURE";
static const char st_12[]	= "CALL";
static const char st_13[]	= "EVALUTE-LISP-PROCEDURE";
static const char st_14[]	= "INIT-LOGGER-PROCEDURE";
static const char st_15[]	= "CLOSE-LOGGER-PROCEDURE";

