/* Generated by           cobc 2.0.0 */
/* Generated from         cisp.cbl */
/* Generated at           Apr 22 2017 23:36:32 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\cisp.exe -std=default -Wall -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin cisp.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x11,   9,   0, 0x0041, NULL};


/* Constants */
static const cob_field c_1	= {9, (cob_u8_ptr)"TOKENIZER", &a_1};
static const cob_field c_2	= {18, (cob_u8_ptr)"Starting Tokenizer", &a_1};
static const cob_field c_3	= {4, (cob_u8_ptr)"LISP", &a_1};
static const cob_field c_4	= {25, (cob_u8_ptr)"Starting Lisp Evalutation", &a_1};


/* Strings */
static const char st_1[]	= "cisp.cbl";
static const char st_2[]	= "MAIN-PROCEDURE";
static const char st_3[]	= "MOVE";
static const char st_4[]	= "CALL";
static const char st_5[]	= "GOBACK";

