/* Generated by           cobc 2.0.0 */
/* Generated from         cisp-error.cbl */
/* Generated at           Apr 24 2017 19:12:42 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\cisp-error.dll -std=default -Wall -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin cisp-error.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"cisp-error.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 24 2017 19:12:42"
#define  COB_MODULE_DATE		20170424
#define  COB_MODULE_TIME		191242

/* Global variables */
#include "cisp-error.c.h"

/* Function prototypes */

__declspec(dllexport) int		CISP__ERROR (cob_u8_t *, cob_u8_t *);
static int		CISP__ERROR_ (const int, cob_u8_t *, cob_u8_t *);

/* Functions */

/* PROGRAM-ID 'CISP-ERROR' */

/* ENTRY 'CISP__ERROR' */

int
CISP__ERROR (cob_u8_t *b_11, cob_u8_t *b_12)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
	cob_call_params = 2;
  };

  return CISP__ERROR_ (0, b_11, b_12);
}

static int
CISP__ERROR_ (const int entry, cob_u8_t *b_11, cob_u8_t *b_12)
{
  /* Program local variables */
  #include "cisp-error.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_11 = NULL;
  case 1:
  	b_12 = NULL;
  default:
	break;
  }

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 31        : Entry     CISP-ERROR              : cisp-error.cbl */
  l_2:;

  /* Line: 31        : Paragraph MAIN-PROCEDURE          : cisp-error.cbl */

  /* Line: 32        : EVALUATE           : cisp-error.cbl */
  cob_set_location (st_1, 32, NULL, st_2, st_3);

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_11, b_11), (cob_field *)&c_1) == 0))
  {

    /* Line: 34        : PERFORM            : cisp-error.cbl */
    cob_set_location (st_1, 34, NULL, st_2, st_4);
    /* PERFORM THROW-ERROR-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_10;
    goto l_6;
    l_10:
    frame_ptr--;
    goto l_5;
  }

  /* End EVALUATE */
  l_5:;

  /* Line: 35        : Paragraph THROW-ERROR-PROCEDURE   : cisp-error.cbl */
  l_6:;

  /* Line: 36        : DISPLAY            : cisp-error.cbl */
  cob_set_location (st_1, 36, NULL, st_5, st_6);
  cob_display (0, 1, 1, COB_SET_DATA (f_13, b_12));

  /* Line: 37        : DISPLAY            : cisp-error.cbl */
  cob_set_location (st_1, 37, NULL, st_5, st_6);
  cob_display (0, 1, 1, COB_SET_DATA (f_16, b_12 + 41));

  /* Line: 38        : IF                 : cisp-error.cbl */
  cob_set_location (st_1, 38, NULL, st_5, st_7);
  if (((int)(int)(*(b_12 + 40) - 89) == 0))
  {

    /* Line: 39        : PERFORM            : cisp-error.cbl */
    cob_set_location (st_1, 39, NULL, st_5, st_4);
    /* PERFORM END-CISP-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_11;
    goto l_7;
    l_11:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 41        : Paragraph END-CISP-PROCEDURE      : cisp-error.cbl */
  l_7:;

  /* Line: 42        : PERFORM            : cisp-error.cbl */
  cob_set_location (st_1, 42, NULL, st_8, st_4);
  /* PERFORM LOG-ERROR-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_12;
  goto l_8;
  l_12:
  frame_ptr--;

  /* Line: 43        : PERFORM            : cisp-error.cbl */
  cob_set_location (st_1, 43, NULL, st_8, st_4);
  /* PERFORM CLOSE-OPEN-FILES-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 9;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_9;
  l_13:
  frame_ptr--;

  /* Line: 44        : STOP RUN           : cisp-error.cbl */
  cob_set_location (st_1, 44, NULL, st_8, st_9);
  cob_stop_run (b_1);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 45        : Paragraph LOG-ERROR-PROCEDURE     : cisp-error.cbl */
  l_8:;

  /* Line: 47        : MOVE               : cisp-error.cbl */
  cob_set_location (st_1, 47, NULL, st_10, st_11);
  memcpy (b_6, "ADD  ", 5);

  /* Line: 48        : MOVE               : cisp-error.cbl */
  cob_set_location (st_1, 48, NULL, st_10, st_11);
  cob_move ((cob_field *)&c_2, &f_8);

  /* Line: 50        : STRING             : cisp-error.cbl */
  cob_set_location (st_1, 50, NULL, st_10, st_12);
  cob_string_init (&f_9, NULL);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_DATA (f_13, b_12));
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_3);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_DATA (f_16, b_12 + 41));
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_4);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_DATA (f_14, b_12 + 40));
  cob_string_finish ();

  /* Line: 56        : CALL               : cisp-error.cbl */
  cob_set_location (st_1, 56, NULL, st_10, st_13);
  cob_procedure_params[0] = &f_6;
  cob_procedure_params[1] = &f_7;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_6, b_7);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 57        : Paragraph CLOSE-OPEN-FILES-PROCEDURE: cisp-error.cbl */
  l_9:;

  /* Line: 58        : MOVE               : cisp-error.cbl */
  cob_set_location (st_1, 58, NULL, st_14, st_11);
  memcpy (b_10, "STACK-FILE-STATUS             ", 30);

  /* Line: 59        : CALL               : cisp-error.cbl */
  cob_set_location (st_1, 59, NULL, st_14, st_13);
  cob_procedure_params[0] = &f_10;
  cob_glob_ptr->cob_call_params = 1;
  if (unlikely(call_RECURSION.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_RECURSION.funcvoid = cob_resolve_cobol ("RECURSION", 0, 1);
  }
  b_1 = ((int (*)(void *))call_RECURSION.funcint) (b_10);

  /* Line: 60        : DISPLAY            : cisp-error.cbl */
  cob_set_location (st_1, 60, NULL, st_14, st_6);
  cob_display (0, 1, 2, &c_5, &f_10);

  /* Line: 61        : IF                 : cisp-error.cbl */
  cob_set_location (st_1, 61, NULL, st_14, st_7);
  if (((int)cob_cmp (&f_10, (cob_field *)&c_6) == 0))
  {

    /* Line: 62        : MOVE               : cisp-error.cbl */
    cob_set_location (st_1, 62, NULL, st_14, st_11);
    cob_move ((cob_field *)&c_7, &f_10);

    /* Line: 63        : CALL               : cisp-error.cbl */
    cob_set_location (st_1, 63, NULL, st_14, st_13);
    cob_procedure_params[0] = &f_10;
    cob_glob_ptr->cob_call_params = 1;
    if (unlikely(call_RECURSION.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
      call_RECURSION.funcvoid = cob_resolve_cobol ("RECURSION", 0, 1);
    }
    b_1 = ((int (*)(void *))call_RECURSION.funcint) (b_10);
  }

  /* Line: 65        : MOVE               : cisp-error.cbl */
  cob_set_location (st_1, 65, NULL, st_14, st_11);
  memcpy (b_6, "CLOSE", 5);

  /* Line: 66        : CALL               : cisp-error.cbl */
  cob_set_location (st_1, 66, NULL, st_14, st_13);
  cob_procedure_params[0] = &f_6;
  cob_procedure_params[1] = &f_7;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_6, b_7);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  /* Initialize module structure */
  module->module_name = "CISP-ERROR";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())CISP__ERROR;
  module->module_cancel.funcptr = (void *(*)())CISP__ERROR_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_6, 32, 5);
  memset (b_7, 32, 140);
  memset (b_10, 32, 30);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  call_RECURSION.funcvoid = NULL;
  call_LOGGER.funcvoid = NULL;
  b_1 = 0;
  cob_cache_free (module);
  module = NULL;

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'CISP-ERROR' */

/* End functions */

