/* Generated by           cobc 2.0.0 */
/* Generated from         cisp.cbl */
/* Generated at           Apr 27 2017 17:51:17 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\cisp.exe -std=default -Wall -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin cisp.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"cisp.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 27 2017 17:51:17"
#define  COB_MODULE_DATE		20170427
#define  COB_MODULE_TIME		175117

/* Global variables */
#include "cisp.c.h"

/* Function prototypes */

static int		CISP ();
static int		CISP_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CISP ());
}

/* Functions */

/* PROGRAM-ID 'CISP' */

/* ENTRY 'CISP' */

static int
CISP ()
{
  return CISP_ (0);
}

static int
CISP_ (const int entry)
{
  /* Program local variables */
  #include "cisp.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 40        : Entry     CISP                    : cisp.cbl */
  l_2:;

  /* Line: 40        : Paragraph MAIN-PROCEDURE          : cisp.cbl */

  /* Line: 41        : PERFORM            : cisp.cbl */
  cob_set_location (st_1, 41, NULL, st_2, st_3);
  /* PERFORM INIT-LOGGER-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_10;
  goto l_8;
  l_10:
  frame_ptr--;

  /* Line: 42        : PERFORM            : cisp.cbl */
  cob_set_location (st_1, 42, NULL, st_2, st_3);
  /* PERFORM READ-CMD-LINE-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_11;
  goto l_5;
  l_11:
  frame_ptr--;

  /* Line: 43        : PERFORM            : cisp.cbl */
  cob_set_location (st_1, 43, NULL, st_2, st_3);
  /* PERFORM TOKENIZE-LISP-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_12;
  goto l_6;
  l_12:
  frame_ptr--;

  /* Line: 44        : PERFORM            : cisp.cbl */
  cob_set_location (st_1, 44, NULL, st_2, st_3);
  /* PERFORM EVALUTE-LISP-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_7;
  l_13:
  frame_ptr--;

  /* Line: 45        : PERFORM            : cisp.cbl */
  cob_set_location (st_1, 45, NULL, st_2, st_3);
  /* PERFORM CLOSE-LOGGER-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 9;
  frame_ptr->return_address_ptr = &&l_14;
  goto l_9;
  l_14:
  frame_ptr--;

  /* Line: 46        : GOBACK             : cisp.cbl */
  cob_set_location (st_1, 46, NULL, st_2, st_4);
  goto exit_program;

  /* Line: 47        : Paragraph READ-CMD-LINE-PROCEDURE : cisp.cbl */
  l_5:;

  /* Line: 49        : ACCEPT             : cisp.cbl */
  cob_set_location (st_1, 49, NULL, st_5, st_6);
  cob_accept_arg_number (&f_10);

  /* Line: 50        : ACCEPT             : cisp.cbl */
  cob_set_location (st_1, 50, NULL, st_5, st_6);
  cob_accept_arg_value (&f_9);

  /* Line: 51        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 51, NULL, st_5, st_7);
  memcpy (b_15, b_8, 100);

  /* Line: 52        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 52, NULL, st_5, st_7);
  memcpy (b_11, "ADD  ", 5);

  /* Line: 53        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 53, NULL, st_5, st_7);
  memcpy (b_12, "CISP:READ-CMD-LINE-PROCEDURE            ", 40);

  /* Line: 55        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 55, NULL, st_5, st_7);
  cob_move ((cob_field *)&c_1, &f_14);

  /* Line: 56        : CALL               : cisp.cbl */
  cob_set_location (st_1, 56, NULL, st_5, st_8);
  cob_procedure_params[0] = &f_11;
  cob_procedure_params[1] = &f_12;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_11, b_12);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 57        : Paragraph TOKENIZE-LISP-PROCEDURE : cisp.cbl */
  l_6:;

  /* Line: 59        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 59, NULL, st_9, st_7);
  memcpy (b_11, "ADD  ", 5);

  /* Line: 60        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 60, NULL, st_9, st_7);
  cob_move ((cob_field *)&c_2, &f_13);

  /* Line: 61        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 61, NULL, st_9, st_7);
  cob_move ((cob_field *)&c_3, &f_14);

  /* Line: 62        : CALL               : cisp.cbl */
  cob_set_location (st_1, 62, NULL, st_9, st_8);
  cob_procedure_params[0] = &f_11;
  cob_procedure_params[1] = &f_12;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_11, b_12);

  /* Line: 63        : CALL               : cisp.cbl */
  cob_set_location (st_1, 63, NULL, st_9, st_8);
  {
    cob_content	content_2;
    cob_field	content_fb_2 = { 4, content_2.data, &a_4 };

    content_2.dataint = 100;
    cob_procedure_params[0] = &f_15;
    cob_procedure_params[1] = &content_fb_2;
    cob_procedure_params[2] = &f_17;
    cob_glob_ptr->cob_call_params = 3;
    if (unlikely(call_TOKENIZER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
      call_TOKENIZER.funcvoid = cob_resolve_cobol ("TOKENIZER", 0, 1);
    }
    b_1 = ((int (*)(void *, void *, void *))call_TOKENIZER.funcint) (b_15, content_2.data, b_17);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 65        : Paragraph EVALUTE-LISP-PROCEDURE  : cisp.cbl */
  l_7:;

  /* Line: 67        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 67, NULL, st_10, st_7);
  memcpy (b_11, "ADD  ", 5);

  /* Line: 68        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 68, NULL, st_10, st_7);
  cob_move ((cob_field *)&c_4, &f_13);

  /* Line: 69        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 69, NULL, st_10, st_7);
  cob_move ((cob_field *)&c_5, &f_14);

  /* Line: 70        : CALL               : cisp.cbl */
  cob_set_location (st_1, 70, NULL, st_10, st_8);
  cob_procedure_params[0] = &f_11;
  cob_procedure_params[1] = &f_12;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_11, b_12);

  /* Line: 71        : CALL               : cisp.cbl */
  cob_set_location (st_1, 71, NULL, st_10, st_8);
  cob_procedure_params[0] = &f_17;
  cob_glob_ptr->cob_call_params = 1;
  if (unlikely(call_LISP.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LISP.funcvoid = cob_resolve_cobol ("LISP", 0, 1);
  }
  b_1 = ((int (*)(void *))call_LISP.funcint) (b_17);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 72        : Paragraph INIT-LOGGER-PROCEDURE   : cisp.cbl */
  l_8:;

  /* Line: 73        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 73, NULL, st_11, st_7);
  memcpy (b_11, "OPEN ", 5);

  /* Line: 74        : CALL               : cisp.cbl */
  cob_set_location (st_1, 74, NULL, st_11, st_8);
  cob_procedure_params[0] = &f_11;
  cob_procedure_params[1] = &f_12;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_11, b_12);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 75        : Paragraph CLOSE-LOGGER-PROCEDURE  : cisp.cbl */
  l_9:;

  /* Line: 76        : MOVE               : cisp.cbl */
  cob_set_location (st_1, 76, NULL, st_12, st_7);
  memcpy (b_11, "CLOSE", 5);

  /* Line: 77        : CALL               : cisp.cbl */
  cob_set_location (st_1, 77, NULL, st_12, st_8);
  cob_procedure_params[0] = &f_11;
  cob_procedure_params[1] = &f_12;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_11, b_12);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;


  /* Paragraph Default Error Handler   */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "CISP";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())CISP;
  module->module_cancel.funcptr = (void *(*)())CISP_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_8, 32, 100);
  memset (b_8 + 100, 48, 4);
  memset (b_11, 32, 5);
  memset (b_12, 32, 140);
  memset (b_15, 32, 100);
  memset (b_17, 48, 4);
  memset (b_17 + 4 + 50 * 0, 32, 5000);
  memset (b_17 + 5004 + 2 * 0, 48, 200);


  if (!h_TESTS_FILE)
  {
    h_TESTS_FILE = cob_cache_malloc (sizeof(cob_file));
  }
  h_TESTS_FILE->select_name = (const char *)"TESTS-FILE";
  h_TESTS_FILE->file_status = h_TESTS_FILE_status;
  memset (h_TESTS_FILE_status, '0', 2);
  h_TESTS_FILE->assign = (cob_field *)&c_6;
  h_TESTS_FILE->record = &f_7;
  h_TESTS_FILE->variable_record = NULL;
  h_TESTS_FILE->record_min = 0;
  h_TESTS_FILE->record_max = 100;
  h_TESTS_FILE->nkeys = 0;
  h_TESTS_FILE->keys = NULL;
  h_TESTS_FILE->file = NULL;
  h_TESTS_FILE->fd = -1;
  h_TESTS_FILE->organization = 1;
  h_TESTS_FILE->access_mode = 1;
  h_TESTS_FILE->lock_mode = 0;
  h_TESTS_FILE->open_mode = 0;
  h_TESTS_FILE->flag_optional = 0;
  h_TESTS_FILE->last_open_mode = 0;
  h_TESTS_FILE->flag_operation = 0;
  h_TESTS_FILE->flag_nonexistent = 0;
  h_TESTS_FILE->flag_end_of_file = 0;
  h_TESTS_FILE->flag_begin_of_file = 0;
  h_TESTS_FILE->flag_first_read = 0;
  h_TESTS_FILE->flag_read_done = 0;
  h_TESTS_FILE->flag_select_features = 0;
  h_TESTS_FILE->flag_needs_nl = 0;
  h_TESTS_FILE->flag_needs_top = 0;
  h_TESTS_FILE->file_version = 1;

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'CISP' */

/* End functions */

