/* Generated by           cobc 2.0.0 */
/* Generated from         lisp.cbl */
/* Generated at           Apr 27 2017 17:51:26 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\lisp.dll -std=default -Wall -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin lisp.cbl */

/* Program local variables for 'LISP' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	call_RECURSION;
static cob_call_union	call_LOGGER;
static cob_call_union	call_CISP__ERROR;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_6[4] __attribute__((aligned));	/* WS-SYMBOL-TABLE-INDEX */
static cob_u8_t	b_7[20] __attribute__((aligned));	/* WS-CURR-COMMAND */
static cob_u8_t	b_8[20] __attribute__((aligned));	/* WS-CURRENT-VALUE */
static cob_u8_t	b_10[1] __attribute__((aligned));	/* WS-INIT-COMMAND */
static cob_u8_t	b_12[30] __attribute__((aligned));	/* WS-CISP-ERROR-FLAG */
static cob_u8_t	b_13[141] __attribute__((aligned));	/* WS-ERROR */
static cob_u8_t	b_18[5] __attribute__((aligned));	/* WS-LOG-OPERATION-FLAG */
static cob_u8_t	b_19[140] __attribute__((aligned));	/* WS-LOG-RECORD */
static cob_u8_t	b_22[30] __attribute__((aligned));	/* WS-RECURSION-FLAG */
static cob_u8_t	b_23[41] __attribute__((aligned));	/* WS-RECURSION-OBJECT */

/* End of data storage */


/* Fields */
static cob_field f_6	= {4, b_6, &a_2};	/* WS-SYMBOL-TABLE-INDEX */
static cob_field f_7	= {20, b_7, &a_1};	/* WS-CURR-COMMAND */
static cob_field f_8	= {20, b_8, &a_1};	/* WS-CURRENT-VALUE */
static cob_field f_9	= {20, b_8, &a_4};	/* WS-CURRENT-VALUE-NUMERIC */
static cob_field f_12	= {30, b_12, &a_1};	/* WS-CISP-ERROR-FLAG */
static cob_field f_13	= {141, b_13, &a_3};	/* WS-ERROR */
static cob_field f_14	= {40, b_13, &a_1};	/* WS-ERROR-NAME */
static cob_field f_17	= {100, b_13 + 41, &a_1};	/* WS-ERROR-MESSAGE */
static cob_field f_18	= {5, b_18, &a_1};	/* WS-LOG-OPERATION-FLAG */
static cob_field f_19	= {140, b_19, &a_3};	/* WS-LOG-RECORD */
static cob_field f_20	= {40, b_19, &a_1};	/* WS-LOG-RECORD-FUNCTION-NAME */
static cob_field f_21	= {100, b_19 + 40, &a_1};	/* WS-LOG-RECORD-MESSAGE */
static cob_field f_22	= {30, b_22, &a_1};	/* WS-RECURSION-FLAG */
static cob_field f_23	= {41, b_23, &a_3};	/* WS-RECURSION-OBJECT */
static cob_field f_24	= {20, b_23, &a_1};	/* WS-COMMAND-NAME */
static cob_field f_25	= {20, b_23 + 20, &a_1};	/* WS-COMMAND-RESULT */
static cob_field f_26	= {20, b_23 + 20, &a_4};	/* WS-COMMAND-RESULT-NUMERIC */

/* End of fields */

