/* Generated by           cobc 2.0.0 */
/* Generated from         lisp.cbl */
/* Generated at           Apr 22 2017 14:59:08 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\lisp.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin lisp.cbl */

/* Program local variables for 'LISP' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	call_RECURSION;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_6[5] __attribute__((aligned));	/* WS-LOG-OPERATION-FLAG */
static cob_u8_t	b_7[140] __attribute__((aligned));	/* WS-LOG-RECORD */
static cob_u8_t	b_10[5] __attribute__((aligned));	/* WS-RECURSION-FLAG */

/* End of data storage */


/* Fields */
static cob_field f_8	= {40, b_7, &a_1};	/* WS-LOG-RECORD-FUNCTION-NAME */
static cob_field f_10	= {5, b_10, &a_1};	/* WS-RECURSION-FLAG */

/* End of fields */

