/* Generated by           cobc 2.0.0 */
/* Generated from         LISP.cbl */
/* Generated at           Apr 22 2017 16:28:41 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\LISP.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin LISP.cbl */

/* Program local variables for 'LISP' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	call_RECURSION;
static cob_call_union	call_LOGGER;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_6[4] __attribute__((aligned));	/* WS-SYMBOL-TABLE-INDEX */
static cob_u8_t	b_7[100] __attribute__((aligned));	/* WS-CURR-COMMAND */
static cob_u8_t	b_8[5] __attribute__((aligned));	/* WS-LOG-OPERATION-FLAG */
static cob_u8_t	b_9[140] __attribute__((aligned));	/* WS-LOG-RECORD */
static cob_u8_t	b_12[30] __attribute__((aligned));	/* WS-RECURSION-FLAG */
static cob_u8_t	b_13[41] __attribute__((aligned));	/* WS-RECURSION-OBJECT */

/* End of data storage */


/* Fields */
static cob_field f_6	= {4, b_6, &a_3};	/* WS-SYMBOL-TABLE-INDEX */
static cob_field f_7	= {100, b_7, &a_1};	/* WS-CURR-COMMAND */
static cob_field f_8	= {5, b_8, &a_1};	/* WS-LOG-OPERATION-FLAG */
static cob_field f_9	= {140, b_9, &a_4};	/* WS-LOG-RECORD */
static cob_field f_10	= {40, b_9, &a_1};	/* WS-LOG-RECORD-FUNCTION-NAME */
static cob_field f_11	= {100, b_9 + 40, &a_1};	/* WS-LOG-RECORD-MESSAGE */
static cob_field f_12	= {30, b_12, &a_1};	/* WS-RECURSION-FLAG */
static cob_field f_13	= {41, b_13, &a_4};	/* WS-RECURSION-OBJECT */
static cob_field f_14	= {20, b_13, &a_1};	/* WS-COMMAND-NAME */
static cob_field f_20	= {1, NULL, &a_2};	/* LS-SYMBOL-TABLE-SIZE */

/* End of fields */

