/* Generated by           cobc 2.0.0 */
/* Generated from         lisp.cbl */
/* Generated at           Apr 22 2017 14:59:08 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\lisp.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin lisp.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"lisp.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 22 2017 14:59:08"
#define  COB_MODULE_DATE		20170422
#define  COB_MODULE_TIME		145908

/* Global variables */
#include "lisp.c.h"

/* Function prototypes */

__declspec(dllexport) int		LISP (cob_u8_t *);
static int		LISP_ (const int, cob_u8_t *);

/* Functions */

/* PROGRAM-ID 'LISP' */

/* ENTRY 'LISP' */

int
LISP (cob_u8_t *b_11)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
	cob_call_params = 1;
  };

  return LISP_ (0, b_11);
}

static int
LISP_ (const int entry, cob_u8_t *b_11)
{
  /* Program local variables */
  #include "lisp.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_11 = NULL;
  default:
	break;
  }

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 28        : Entry     LISP                    : lisp.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 28);
  cob_trace_section (st_3, st_1, 28);

  /* Line: 28        : Paragraph MAIN-PROCEDURE          : lisp.cbl */
  cob_trace_section (st_4, st_1, 28);

  /* Line: 29        : DISPLAY            : lisp.cbl */
  cob_set_location (st_1, 29, NULL, st_5, st_6);
  cob_display (0, 1, 1, &c_1);

  /* Line: 31        : MOVE               : lisp.cbl */
  cob_set_location (st_1, 31, NULL, st_5, st_7);
  memcpy (b_10, "INIT ", 5);

  /* Line: 32        : CALL               : lisp.cbl */
  cob_set_location (st_1, 32, NULL, st_5, st_8);
  cob_procedure_params[0] = &f_10;
  cob_glob_ptr->cob_call_params = 1;
  if (unlikely(call_RECURSION.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_RECURSION.funcvoid = cob_resolve_cobol ("RECURSION", 0, 1);
  }
  b_1 = ((int (*)(void *))call_RECURSION.funcint) (b_10);

  /* Line: 33        : GOBACK             : lisp.cbl */
  cob_set_location (st_1, 33, NULL, st_5, st_9);
  goto exit_program;

  /* Line: 34        : Paragraph EVALUATE-LISP-PRCEDURE  : lisp.cbl */
  cob_trace_section (st_10, st_1, 34);

  /* Line: 50        : MOVE               : lisp.cbl */
  cob_set_location (st_1, 50, NULL, st_11, st_7);
  cob_move ((cob_field *)&c_2, &f_8);

  /* Line: 87        : MOVE               : lisp.cbl */
  cob_set_location (st_1, 87, NULL, st_11, st_7);
  cob_move ((cob_field *)&c_3, &f_8);

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_12, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  /* Initialize module structure */
  module->module_name = "LISP";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())LISP;
  module->module_cancel.funcptr = (void *(*)())LISP_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_6, 32, 5);
  memset (b_7, 32, 140);
  memset (b_10, 32, 5);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  call_RECURSION.funcvoid = NULL;
  b_1 = 0;
  cob_cache_free (module);
  module = NULL;

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'LISP' */

/* End functions */

