/* Generated by           cobc 2.0.0 */
/* Generated from         logger.cbl */
/* Generated at           Apr 22 2017 20:53:14 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\logger.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin logger.cbl */

/* Program local variables for 'LOGGER' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File LOG-FILE */
static cob_file		*h_LOG_FILE = NULL;
static unsigned char	h_LOG_FILE_status[4];

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_10[150] __attribute__((aligned));	/* LOG-FILE Record */
static cob_u8_t	b_11[20] __attribute__((aligned));	/* WS-LOG-FILE-NAME */

/* End of data storage */


/* Fields */
static cob_field f_6	= {150, b_10, &a_2};	/* LOG-RECORD */
static cob_field f_7	= {10, b_10, &a_3};	/* LOG-RECORD-ID */
static cob_field f_8	= {40, b_10 + 10, &a_1};	/* LOG-RECORD-FUNCTION-NAME */
static cob_field f_9	= {100, b_10 + 50, &a_1};	/* LOG-RECORD-MESSAGE */
static cob_field f_10	= {150, b_10, &a_1};	/* LOG-FILE Record */
static cob_field f_11	= {20, b_11, &a_1};	/* WS-LOG-FILE-NAME */
static cob_field f_12	= {5, NULL, &a_1};	/* LS-LOG-OPERATION-FLAG */

/* End of fields */

