/* Generated by           cobc 2.0.0 */
/* Generated from         logger.cbl */
/* Generated at           Apr 22 2017 20:53:14 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\logger.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin logger.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"logger.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 22 2017 20:53:14"
#define  COB_MODULE_DATE		20170422
#define  COB_MODULE_TIME		205314

/* Global variables */
#include "logger.c.h"

/* Function prototypes */

__declspec(dllexport) int		LOGGER (cob_u8_t *, cob_u8_t *);
static int		LOGGER_ (const int, cob_u8_t *, cob_u8_t *);

/* Functions */

/* PROGRAM-ID 'LOGGER' */

/* ENTRY 'LOGGER' */

int
LOGGER (cob_u8_t *b_12, cob_u8_t *b_13)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
	cob_call_params = 2;
  };

  return LOGGER_ (0, b_12, b_13);
}

static int
LOGGER_ (const int entry, cob_u8_t *b_12, cob_u8_t *b_13)
{
  /* Program local variables */
  #include "logger.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_12 = NULL;
  case 1:
  	b_13 = NULL;
  default:
	break;
  }

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 29        : Entry     LOGGER                  : logger.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 29);
  cob_trace_section (st_3, st_1, 29);

  /* Line: 29        : Paragraph MAIN-PROCEDURE          : logger.cbl */
  cob_trace_section (st_4, st_1, 29);

  /* Line: 30        : EVALUATE           : logger.cbl */
  cob_set_location (st_1, 30, NULL, st_5, st_6);

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_12, b_12), (cob_field *)&c_1) == 0))
  {

    /* Line: 32        : PERFORM            : logger.cbl */
    cob_set_location (st_1, 32, NULL, st_5, st_7);
    /* PERFORM LOG-INIT-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_10;
    goto l_6;
    l_10:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN */

  if (((int)memcmp (b_12, (cob_u8_ptr)"CLOSE", 5) == 0))
  {

    /* Line: 34        : PERFORM            : logger.cbl */
    cob_set_location (st_1, 34, NULL, st_5, st_7);
    /* PERFORM LOG-CLOSE-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_11;
    goto l_9;
    l_11:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_12, b_12), (cob_field *)&c_2) == 0))
  {

    /* Line: 36        : PERFORM            : logger.cbl */
    cob_set_location (st_1, 36, NULL, st_5, st_7);
    /* PERFORM LOG-WRITE-TO-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_12;
    goto l_7;
    l_12:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN OTHER */

  /* Line: 38        : PERFORM            : logger.cbl */
  cob_set_location (st_1, 38, NULL, st_5, st_7);
  /* PERFORM LOG-FLAG-ERROR-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_8;
  l_13:
  frame_ptr--;

  /* End EVALUATE */
  l_5:;

  /* Line: 39        : GOBACK             : logger.cbl */
  cob_set_location (st_1, 39, NULL, st_5, st_8);
  goto exit_program;

  /* Line: 40        : Paragraph LOG-INIT-PROCEDURE      : logger.cbl */
  l_6:;
  cob_trace_section (st_9, st_1, 40);

  /* Line: 41        : MOVE               : logger.cbl */
  cob_set_location (st_1, 41, NULL, st_10, st_11);
  memcpy (b_11, "..\\logs\\log.data    ", 20);

  /* Line: 42        : OPEN               : logger.cbl */
  cob_set_location (st_1, 42, NULL, st_10, st_12);
  cob_open (h_LOG_FILE, 2, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_1;
    l_14:
    frame_ptr--;
  }

  /* Line: 43        : MOVE               : logger.cbl */
  cob_set_location (st_1, 43, NULL, st_10, st_11);
  memcpy (b_10, "0000000001", 10);

  /* Line: 44        : MOVE               : logger.cbl */
  cob_set_location (st_1, 44, NULL, st_10, st_11);
  cob_move ((cob_field *)&c_3, &f_8);

  /* Line: 45        : MOVE               : logger.cbl */
  cob_set_location (st_1, 45, NULL, st_10, st_11);
  cob_move ((cob_field *)&c_4, &f_9);

  /* Line: 46        : WRITE              : logger.cbl */
  cob_set_location (st_1, 46, NULL, st_10, st_13);
  cob_write (h_LOG_FILE, &f_6, 0x210001, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_1;
    l_15:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 47        : Paragraph LOG-WRITE-TO-PROCEDURE  : logger.cbl */
  l_7:;
  cob_trace_section (st_14, st_1, 47);

  /* Line: 48        : ADD                : logger.cbl */
  cob_set_location (st_1, 48, NULL, st_15, st_16);
  cob_check_numeric (&f_7, "LOG-RECORD-ID");
  cob_add_int (&f_7, 1, 0);

  /* Line: 49        : MOVE               : logger.cbl */
  cob_set_location (st_1, 49, NULL, st_15, st_11);
  memmove (b_10 + 10, b_13, 40);

  /* Line: 50        : MOVE               : logger.cbl */
  cob_set_location (st_1, 50, NULL, st_15, st_11);
  memmove (b_10 + 50, b_13 + 40, 100);

  /* Line: 51        : WRITE              : logger.cbl */
  cob_set_location (st_1, 51, NULL, st_15, st_13);
  cob_write (h_LOG_FILE, &f_6, 0x210001, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_1;
    l_16:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 52        : Paragraph LOG-FLAG-ERROR-PROCEDURE: logger.cbl */
  l_8:;
  cob_trace_section (st_17, st_1, 52);

  /* Line: 53        : DISPLAY            : logger.cbl */
  cob_set_location (st_1, 53, NULL, st_18, st_19);
  cob_display (0, 1, 1, &c_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 54        : Paragraph LOG-CLOSE-PROCEDURE     : logger.cbl */
  l_9:;
  cob_trace_section (st_20, st_1, 54);

  /* Line: 55        : ADD                : logger.cbl */
  cob_set_location (st_1, 55, NULL, st_21, st_16);
  cob_check_numeric (&f_7, "LOG-RECORD-ID");
  cob_add_int (&f_7, 1, 0);

  /* Line: 56        : MOVE               : logger.cbl */
  cob_set_location (st_1, 56, NULL, st_21, st_11);
  memcpy (b_10 + 10, "LOGGER:LOG-CLOSE-PROCEDURE              ", 40);

  /* Line: 58        : MOVE               : logger.cbl */
  cob_set_location (st_1, 58, NULL, st_21, st_11);
  cob_move ((cob_field *)&c_6, &f_9);

  /* Line: 59        : WRITE              : logger.cbl */
  cob_set_location (st_1, 59, NULL, st_21, st_13);
  cob_write (h_LOG_FILE, &f_6, 0x210001, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_17;
    goto l_1;
    l_17:
    frame_ptr--;
  }

  /* Line: 60        : CLOSE              : logger.cbl */
  cob_set_location (st_1, 60, NULL, st_21, st_22);
  cob_close (h_LOG_FILE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_23, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;


  /* Paragraph Default Error Handler   */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  /* Initialize module structure */
  module->module_name = "LOGGER";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())LOGGER;
  module->module_cancel.funcptr = (void *(*)())LOGGER_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_11, 32, 20);


  if (!h_LOG_FILE)
  {
    h_LOG_FILE = cob_cache_malloc (sizeof(cob_file));
  }
  h_LOG_FILE->select_name = (const char *)"LOG-FILE";
  h_LOG_FILE->file_status = h_LOG_FILE_status;
  memset (h_LOG_FILE_status, '0', 2);
  h_LOG_FILE->assign = &f_11;
  h_LOG_FILE->record = &f_10;
  h_LOG_FILE->variable_record = NULL;
  h_LOG_FILE->record_min = 0;
  h_LOG_FILE->record_max = 150;
  h_LOG_FILE->nkeys = 0;
  h_LOG_FILE->keys = NULL;
  h_LOG_FILE->file = NULL;
  h_LOG_FILE->fd = -1;
  h_LOG_FILE->organization = 1;
  h_LOG_FILE->access_mode = 1;
  h_LOG_FILE->lock_mode = 0;
  h_LOG_FILE->open_mode = 0;
  h_LOG_FILE->flag_optional = 1;
  h_LOG_FILE->last_open_mode = 0;
  h_LOG_FILE->flag_operation = 0;
  h_LOG_FILE->flag_nonexistent = 0;
  h_LOG_FILE->flag_end_of_file = 0;
  h_LOG_FILE->flag_begin_of_file = 0;
  h_LOG_FILE->flag_first_read = 0;
  h_LOG_FILE->flag_read_done = 0;
  h_LOG_FILE->flag_select_features = 0;
  h_LOG_FILE->flag_needs_nl = 0;
  h_LOG_FILE->flag_needs_top = 0;
  h_LOG_FILE->file_version = 1;

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  cob_close (h_LOG_FILE, NULL, COB_CLOSE_NORMAL, 1);
  cob_cache_free (h_LOG_FILE);
  h_LOG_FILE = NULL;
  b_1 = 0;
  cob_cache_free (module);
  module = NULL;

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'LOGGER' */

/* End functions */

