/* Generated by           cobc 2.0.0 */
/* Generated from         recursion.cbl */
/* Generated at           Apr 22 2017 20:54:07 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\recursion.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin recursion.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"recursion.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 22 2017 20:54:07"
#define  COB_MODULE_DATE		20170422
#define  COB_MODULE_TIME		205407

/* Global variables */
#include "recursion.c.h"

/* Function prototypes */

__declspec(dllexport) int		RECURSION (cob_u8_t *, cob_u8_t *);
static int		RECURSION_ (const int, cob_u8_t *, cob_u8_t *);

/* Functions */

/* PROGRAM-ID 'RECURSION' */

/* ENTRY 'RECURSION' */

int
RECURSION (cob_u8_t *b_39, cob_u8_t *b_40)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
	cob_call_params = 2;
  };

  return RECURSION_ (0, b_39, b_40);
}

static int
RECURSION_ (const int entry, cob_u8_t *b_39, cob_u8_t *b_40)
{
  /* Program local variables */
  #include "recursion.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_39 = NULL;
  case 1:
  	b_40 = NULL;
  default:
	break;
  }

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 67        : Entry     RECURSION               : recursion.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 67);
  cob_trace_section (st_3, st_1, 67);

  /* Line: 67        : Paragraph MAIN-PROCEDURE          : recursion.cbl */
  cob_trace_section (st_4, st_1, 67);

  /* Line: 68        : EVALUATE           : recursion.cbl */
  cob_set_location (st_1, 68, NULL, st_5, st_6);

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_39, b_39), (cob_field *)&c_1) == 0))
  {

    /* Line: 70        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 70, NULL, st_5, st_7);
    /* PERFORM INIT-CALL-STACK-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 13;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_13;
    l_20:
    frame_ptr--;

    /* Line: 71        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 71, NULL, st_5, st_7);
    /* PERFORM LOG-INIT-CALL-STACK */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_21;
    goto l_6;
    l_21:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_39, b_39), (cob_field *)&c_2) == 0))
  {

    /* Line: 73        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 73, NULL, st_5, st_7);
    /* PERFORM CALL-STACK-ADD-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 15;
    frame_ptr->return_address_ptr = &&l_22;
    goto l_15;
    l_22:
    frame_ptr--;

    /* Line: 74        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 74, NULL, st_5, st_7);
    /* PERFORM LOG-ADD-TO-CALL-STACK */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_23;
    goto l_7;
    l_23:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_39, b_39), (cob_field *)&c_3) == 0))
  {

    /* Line: 76        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 76, NULL, st_5, st_7);
    /* PERFORM CALL-STACK-GET-TOP-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 17;
    frame_ptr->return_address_ptr = &&l_24;
    goto l_17;
    l_24:
    frame_ptr--;

    /* Line: 77        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 77, NULL, st_5, st_7);
    /* PERFORM LOG-PEEK-CALL-STACK */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_25;
    goto l_8;
    l_25:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_39, b_39), (cob_field *)&c_4) == 0))
  {

    /* Line: 79        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 79, NULL, st_5, st_7);
    /* PERFORM LOG-POP-FROM-CALL-STACK */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_26;
    goto l_9;
    l_26:
    frame_ptr--;

    /* Line: 80        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 80, NULL, st_5, st_7);
    /* PERFORM POP-CALL-STACK-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 18;
    frame_ptr->return_address_ptr = &&l_27;
    goto l_18;
    l_27:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_39, b_39), (cob_field *)&c_5) == 0))
  {

    /* Line: 82        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 82, NULL, st_5, st_7);
    /* PERFORM IS-STACK-EMPTY-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 19;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_19;
    l_28:
    frame_ptr--;

    /* Line: 83        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 83, NULL, st_5, st_7);
    /* PERFORM LOG-IS-EMPTY-CALL-STACK */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 10;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_10;
    l_29:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_39, b_39), (cob_field *)&c_6) == 0))
  {

    /* Line: 85        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 85, NULL, st_5, st_7);
    /* PERFORM PRINT-CALL-STACK-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_30;
    goto l_16;
    l_30:
    frame_ptr--;
    goto l_5;
  }

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_39, b_39), (cob_field *)&c_7) == 0))
  {

    /* Line: 87        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 87, NULL, st_5, st_7);
    /* PERFORM CLOSE-CALL-STACK-PROCEDURE */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 14;
    frame_ptr->return_address_ptr = &&l_31;
    goto l_14;
    l_31:
    frame_ptr--;

    /* Line: 88        : PERFORM            : recursion.cbl */
    cob_set_location (st_1, 88, NULL, st_5, st_7);
    /* PERFORM LOG-CLOSE-CALL-STACK */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_32;
    goto l_11;
    l_32:
    frame_ptr--;
    goto l_5;
  }

  /* End EVALUATE */
  l_5:;

  /* Line: 89        : GOBACK             : recursion.cbl */
  cob_set_location (st_1, 89, NULL, st_5, st_8);
  goto exit_program;

  /* Line: 90        : Paragraph LOG-INIT-CALL-STACK     : recursion.cbl */
  l_6:;
  cob_trace_section (st_9, st_1, 90);

  /* Line: 91        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 91, NULL, st_10, st_11);
  memcpy (b_35, "ADD  ", 5);

  /* Line: 92        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 92, NULL, st_10, st_11);
  cob_move ((cob_field *)&c_8, &f_37);

  /* Line: 93        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 93, NULL, st_10, st_11);
  cob_move ((cob_field *)&c_9, &f_38);

  /* Line: 94        : CALL               : recursion.cbl */
  cob_set_location (st_1, 94, NULL, st_10, st_12);
  cob_procedure_params[0] = &f_35;
  cob_procedure_params[1] = &f_36;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_35, b_36);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 95        : Paragraph LOG-ADD-TO-CALL-STACK   : recursion.cbl */
  l_7:;
  cob_trace_section (st_13, st_1, 95);

  /* Line: 97        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 97, NULL, st_14, st_11);
  memcpy (b_36, "RECURSION:ADD-TO-CALL-STACK             ", 40);

  /* Line: 99        : STRING             : recursion.cbl */
  cob_set_location (st_1, 99, NULL, st_14, st_15);
  cob_string_init (&f_38, NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_7);
  cob_string_delimited (NULL);
  cob_string_append (&f_8);
  cob_string_finish ();

  /* Line: 102       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 102, NULL, st_14, st_11);
  memcpy (b_35, "ADD  ", 5);

  /* Line: 103       : CALL               : recursion.cbl */
  cob_set_location (st_1, 103, NULL, st_14, st_12);
  cob_procedure_params[0] = &f_35;
  cob_procedure_params[1] = &f_36;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_35, b_36);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 104       : Paragraph LOG-PEEK-CALL-STACK     : recursion.cbl */
  l_8:;
  cob_trace_section (st_16, st_1, 104);

  /* Line: 106       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 106, NULL, st_17, st_11);
  memcpy (b_36, "RECURSION:GET-TOP-CALL-STACK            ", 40);

  /* Line: 108       : STRING             : recursion.cbl */
  cob_set_location (st_1, 108, NULL, st_17, st_15);
  cob_string_init (&f_38, NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_7);
  cob_string_delimited (NULL);
  cob_string_append (&f_8);
  cob_string_finish ();

  /* Line: 111       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 111, NULL, st_17, st_11);
  memcpy (b_35, "ADD  ", 5);

  /* Line: 112       : CALL               : recursion.cbl */
  cob_set_location (st_1, 112, NULL, st_17, st_12);
  cob_procedure_params[0] = &f_35;
  cob_procedure_params[1] = &f_36;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_35, b_36);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 113       : Paragraph LOG-POP-FROM-CALL-STACK : recursion.cbl */
  l_9:;
  cob_trace_section (st_18, st_1, 113);

  /* Line: 114       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 114, NULL, st_19, st_11);
  cob_move ((cob_field *)&c_10, &f_37);

  /* Line: 116       : STRING             : recursion.cbl */
  cob_set_location (st_1, 116, NULL, st_19, st_15);
  cob_string_init (&f_38, NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_7);
  cob_string_delimited (NULL);
  cob_string_append (&f_8);
  cob_string_finish ();

  /* Line: 119       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 119, NULL, st_19, st_11);
  memcpy (b_35, "ADD  ", 5);

  /* Line: 120       : CALL               : recursion.cbl */
  cob_set_location (st_1, 120, NULL, st_19, st_12);
  cob_procedure_params[0] = &f_35;
  cob_procedure_params[1] = &f_36;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_35, b_36);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 121       : Paragraph LOG-IS-EMPTY-CALL-STACK : recursion.cbl */
  l_10:;
  cob_trace_section (st_20, st_1, 121);

  /* Line: 122       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 122, NULL, st_21, st_11);
  memcpy (b_36, "RECURSION:IS-EMPTY-CALL-STACK           ", 40);

  /* Line: 124       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 124, NULL, st_21, st_11);
  cob_move (&f_33, &f_38);

  /* Line: 125       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 125, NULL, st_21, st_11);
  memcpy (b_35, "ADD  ", 5);

  /* Line: 126       : CALL               : recursion.cbl */
  cob_set_location (st_1, 126, NULL, st_21, st_12);
  cob_procedure_params[0] = &f_35;
  cob_procedure_params[1] = &f_36;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_35, b_36);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 127       : Paragraph LOG-CLOSE-CALL-STACK    : recursion.cbl */
  l_11:;
  cob_trace_section (st_22, st_1, 127);

  /* Line: 129       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 129, NULL, st_23, st_11);
  memcpy (b_36, "RECURSION:CLOSE-CALL-STACK              ", 40);

  /* Line: 131       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 131, NULL, st_23, st_11);
  cob_move ((cob_field *)&c_11, &f_38);

  /* Line: 132       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 132, NULL, st_23, st_11);
  memcpy (b_35, "ADD  ", 5);

  /* Line: 133       : CALL               : recursion.cbl */
  cob_set_location (st_1, 133, NULL, st_23, st_12);
  cob_procedure_params[0] = &f_35;
  cob_procedure_params[1] = &f_36;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_35, b_36);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 134       : Paragraph LOG-DELETE-FROM-CALL-STACK: recursion.cbl */
  cob_trace_section (st_24, st_1, 134);

  /* Line: 136       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 136, NULL, st_25, st_11);
  memcpy (b_36, "RECURSION:DELETE-FROM-CALL-STACK        ", 40);

  /* Line: 138       : STRING             : recursion.cbl */
  cob_set_location (st_1, 138, NULL, st_25, st_15);
  cob_string_init (&f_38, NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_7);
  cob_string_delimited (NULL);
  cob_string_append (&f_8);
  cob_string_finish ();

  /* Line: 141       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 141, NULL, st_25, st_11);
  memcpy (b_35, "ADD  ", 5);

  /* Line: 142       : CALL               : recursion.cbl */
  cob_set_location (st_1, 142, NULL, st_25, st_12);
  cob_procedure_params[0] = &f_35;
  cob_procedure_params[1] = &f_36;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_35, b_36);

  /* Line: 143       : Paragraph INIT-CALL-STACK-PROCEDURE: recursion.cbl */
  l_13:;
  cob_trace_section (st_26, st_1, 143);

  /* Line: 146       : OPEN               : recursion.cbl */
  cob_set_location (st_1, 146, NULL, st_27, st_28);
  cob_open (h_CALL_STACK, 2, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_33;
    goto l_1;
    l_33:
    frame_ptr--;
  }

  /* Line: 147       : CLOSE              : recursion.cbl */
  cob_set_location (st_1, 147, NULL, st_27, st_29);
  cob_close (h_CALL_STACK, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_34;
    goto l_1;
    l_34:
    frame_ptr--;
  }

  /* Line: 149       : OPEN               : recursion.cbl */
  cob_set_location (st_1, 149, NULL, st_27, st_28);
  cob_open (h_CALL_STACK, 3, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_35;
    goto l_1;
    l_35:
    frame_ptr--;
  }

  /* Line: 150       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 150, NULL, st_27, st_11);
  memcpy (b_25, "00001", 5);

  /* Line: 151       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 151, NULL, st_27, st_11);
  memcpy (b_31, "00001", 5);

  /* Line: 152       : SET                : recursion.cbl */
  cob_set_location (st_1, 152, NULL, st_27, st_30);
  *(b_31 + 5) = 78;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 13)
    goto *frame_ptr->return_address_ptr;

  /* Line: 153       : Paragraph CLOSE-CALL-STACK-PROCEDURE: recursion.cbl */
  l_14:;
  cob_trace_section (st_31, st_1, 153);

  /* Line: 154       : CLOSE              : recursion.cbl */
  cob_set_location (st_1, 154, NULL, st_32, st_29);
  cob_close (h_CALL_STACK, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_36;
    goto l_1;
    l_36:
    frame_ptr--;
  }

  /* Line: 155       : DELETE             : recursion.cbl */
  cob_set_location (st_1, 155, NULL, st_32, st_33);
  cob_delete_file (h_CALL_STACK, NULL);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address_ptr;

  /* Line: 156       : Paragraph CALL-STACK-ADD-PROCEDURE: recursion.cbl */
  l_15:;
  cob_trace_section (st_34, st_1, 156);

  /* Line: 157       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 157, NULL, st_35, st_11);
  cob_check_numeric (&f_25, "WS-CALL-STACK-NEXT-ID");
  memcpy (b_14, b_25, 5);

  /* Line: 158       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 158, NULL, st_35, st_11);
  memmove (b_14 + 5, b_40, 20);

  /* Line: 159       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 159, NULL, st_35, st_11);
  memmove (b_14 + 25, b_40 + 20, 20);

  /* Line: 160       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 160, NULL, st_35, st_11);
  *(b_14 + 50) = *(b_40 + 40);

  /* Line: 161       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 161, NULL, st_35, st_11);
  cob_check_numeric (&f_7, "COMMAND-ID");
  memcpy (b_14 + 45, b_14, 5);

  /* Line: 162       : SUBTRACT           : recursion.cbl */
  cob_set_location (st_1, 162, NULL, st_35, st_36);
  cob_check_numeric (&f_11, "COMMAND-RETURN-ID");
  cob_sub_int (&f_11, 1, 0);

  /* Line: 163       : WRITE              : recursion.cbl */
  cob_set_location (st_1, 163, NULL, st_35, st_37);
  cob_write (h_CALL_STACK, &f_6, 0, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_37;
    goto l_1;
    l_37:
    frame_ptr--;
  }

  /* Line: 164       : IF                 : recursion.cbl */
  cob_set_location (st_1, 164, NULL, st_35, st_38);
  if (((int)(int)(*(b_31 + 5) - 89) == 0))
  {

    /* Line: 165       : MOVE               : recursion.cbl */
    cob_set_location (st_1, 165, NULL, st_35, st_11);
    cob_check_numeric (&f_25, "WS-CALL-STACK-NEXT-ID");
    memcpy (b_31, b_25, 5);
  }

  /* Line: 167       : ADD                : recursion.cbl */
  cob_set_location (st_1, 167, NULL, st_35, st_39);
  cob_check_numeric (&f_25, "WS-CALL-STACK-NEXT-ID");
  cob_add_int (&f_25, 1, 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Line: 168       : Paragraph PRINT-CALL-STACK-PROCEDURE: recursion.cbl */
  l_16:;
  cob_trace_section (st_40, st_1, 168);

  /* Line: 169       : DISPLAY            : recursion.cbl */
  cob_set_location (st_1, 169, NULL, st_41, st_42);
  cob_display (0, 1, 1, &c_12);

  /* Line: 170       : DISPLAY            : recursion.cbl */
  cob_set_location (st_1, 170, NULL, st_41, st_42);
  cob_display (0, 1, 5, &c_13, &c_14, &c_15, &c_16, &c_17);

  /* Line: 174       : PERFORM            : recursion.cbl */
  cob_set_location (st_1, 174, NULL, st_41, st_7);
  memcpy (b_14, "00001", 5);
  for (;;)
  {
    if (((int)memcmp (b_14, b_25, 5) == 0))
      break;

    /* Line: 176       : READ               : recursion.cbl */
    cob_set_location (st_1, 176, NULL, st_41, st_43);
    cob_read (h_CALL_STACK, &f_7, NULL, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0506)
      {

        /* Line: 178       : DISPLAY            : recursion.cbl */
        cob_set_location (st_1, 178, NULL, st_41, st_42);
        cob_display (0, 1, 1, &c_18);
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_38;
        goto l_1;
        l_38:
        frame_ptr--;
      }
    }
    else
    {
      cob_move (&f_14, &f_15);
    }

    /* Line: 180       : DISPLAY            : recursion.cbl */
    cob_set_location (st_1, 180, NULL, st_41, st_42);
    cob_display (0, 1, 13, &f_16, &c_19, &f_17, &c_19, &f_18, &c_19, &f_19, &c_19, &f_20, &c_19, &f_21, &c_19, &f_22);
    cob_add_int (&f_7, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Line: 185       : Paragraph CALL-STACK-GET-TOP-PROCEDURE: recursion.cbl */
  l_17:;
  cob_trace_section (st_44, st_1, 185);

  /* Line: 186       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 186, NULL, st_45, st_11);
  cob_check_numeric (&f_25, "WS-CALL-STACK-NEXT-ID");
  memcpy (b_14, b_25, 5);

  /* Line: 187       : SUBTRACT           : recursion.cbl */
  cob_set_location (st_1, 187, NULL, st_45, st_36);
  cob_check_numeric (&f_7, "COMMAND-ID");
  cob_sub_int (&f_7, 1, 0);

  /* Line: 188       : READ               : recursion.cbl */
  cob_set_location (st_1, 188, NULL, st_45, st_43);
  cob_read (h_CALL_STACK, &f_7, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_39;
    goto l_1;
    l_39:
    frame_ptr--;
  }

  /* Line: 191       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 191, NULL, st_45, st_11);
  memmove (b_40, b_14 + 5, 20);

  /* Line: 192       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 192, NULL, st_45, st_11);
  memmove (b_40 + 20, b_14 + 25, 20);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address_ptr;

  /* Line: 193       : Paragraph POP-CALL-STACK-PROCEDURE: recursion.cbl */
  l_18:;
  cob_trace_section (st_46, st_1, 193);

  /* Line: 194       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 194, NULL, st_47, st_11);
  cob_check_numeric (&f_25, "WS-CALL-STACK-NEXT-ID");
  memcpy (b_14, b_25, 5);

  /* Line: 195       : SUBTRACT           : recursion.cbl */
  cob_set_location (st_1, 195, NULL, st_47, st_36);
  cob_check_numeric (&f_7, "COMMAND-ID");
  cob_sub_int (&f_7, 1, 0);

  /* Line: 196       : READ               : recursion.cbl */
  cob_set_location (st_1, 196, NULL, st_47, st_43);
  cob_read (h_CALL_STACK, &f_7, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_40;
    goto l_1;
    l_40:
    frame_ptr--;
  }

  /* Line: 197       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 197, NULL, st_47, st_11);
  memmove (b_40, b_14 + 5, 20);

  /* Line: 198       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 198, NULL, st_47, st_11);
  memmove (b_40 + 20, b_14 + 25, 20);

  /* Line: 199       : DELETE             : recursion.cbl */
  cob_set_location (st_1, 199, NULL, st_47, st_33);
  cob_delete (h_CALL_STACK, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_41;
    goto l_1;
    l_41:
    frame_ptr--;
  }

  /* Line: 200       : IF                 : recursion.cbl */
  cob_set_location (st_1, 200, NULL, st_47, st_38);
  if (((int)memcmp (b_14, b_31, 5) == 0))
  {

    /* Line: 201       : SET                : recursion.cbl */
    cob_set_location (st_1, 201, NULL, st_47, st_30);
    *(b_31 + 5) = 89;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 18)
    goto *frame_ptr->return_address_ptr;

  /* Line: 203       : Paragraph IS-STACK-EMPTY-PROCEDURE: recursion.cbl */
  l_19:;
  cob_trace_section (st_48, st_1, 203);

  /* Line: 204       : IF                 : recursion.cbl */
  cob_set_location (st_1, 204, NULL, st_49, st_38);
  if (((int)(int)(*(b_31 + 5) - 89) == 0))
  {

    /* Line: 205       : MOVE               : recursion.cbl */
    cob_set_location (st_1, 205, NULL, st_49, st_11);
    cob_move ((cob_field *)&c_20, COB_SET_DATA (f_39, b_39));
  }
  else
  {
    /* ELSE */

    /* Line: 207       : MOVE               : recursion.cbl */
    cob_set_location (st_1, 207, NULL, st_49, st_11);
    cob_move ((cob_field *)&c_21, COB_SET_DATA (f_39, b_39));
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_50, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;


  /* Paragraph Default Error Handler   */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  /* Initialize module structure */
  module->module_name = "RECURSION";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())RECURSION;
  module->module_cancel.funcptr = (void *(*)())RECURSION_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_15, 48, 5);
  memset (b_15 + 5, 32, 40);
  memset (b_15 + 45, 48, 5);
  memset (b_15 + 50, 32, 21);
  *(cob_u8_ptr)(b_24) = 32;
  memset (b_25, 48, 5);
  *(cob_u8_ptr)(b_26) = 32;
  memset (b_28, 32, 20);
  memset (b_28 + 20, 48, 20);
  memset (b_31, 48, 5);
  *(cob_u8_ptr)(b_31 + 5) = 32;
  memset (b_35, 32, 5);
  memset (b_36, 32, 140);


  if (!h_CALL_STACK)
  {
    h_CALL_STACK = cob_cache_malloc (sizeof(cob_file));
  }
  if (!k_CALL_STACK)
  {
    k_CALL_STACK = cob_cache_malloc (sizeof (cob_file_key) * 1);
  }
  k_CALL_STACK->field = &f_7;
  k_CALL_STACK->flag = 0;
  k_CALL_STACK->offset = 0;
  h_CALL_STACK->select_name = (const char *)"CALL-STACK";
  h_CALL_STACK->file_status = h_CALL_STACK_status;
  memset (h_CALL_STACK_status, '0', 2);
  h_CALL_STACK->assign = (cob_field *)&c_22;
  h_CALL_STACK->record = &f_14;
  h_CALL_STACK->variable_record = NULL;
  h_CALL_STACK->record_min = 51;
  h_CALL_STACK->record_max = 51;
  h_CALL_STACK->nkeys = 1;
  h_CALL_STACK->keys = k_CALL_STACK;
  h_CALL_STACK->file = NULL;
  h_CALL_STACK->fd = -1;
  h_CALL_STACK->organization = 3;
  h_CALL_STACK->access_mode = 3;
  h_CALL_STACK->lock_mode = 0;
  h_CALL_STACK->open_mode = 0;
  h_CALL_STACK->flag_optional = 1;
  h_CALL_STACK->last_open_mode = 0;
  h_CALL_STACK->flag_operation = 0;
  h_CALL_STACK->flag_nonexistent = 0;
  h_CALL_STACK->flag_end_of_file = 0;
  h_CALL_STACK->flag_begin_of_file = 0;
  h_CALL_STACK->flag_first_read = 0;
  h_CALL_STACK->flag_read_done = 0;
  h_CALL_STACK->flag_select_features = 0;
  h_CALL_STACK->flag_needs_nl = 0;
  h_CALL_STACK->flag_needs_top = 0;
  h_CALL_STACK->file_version = 1;

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  cob_close (h_CALL_STACK, NULL, COB_CLOSE_NORMAL, 1);
  cob_cache_free (k_CALL_STACK);
  k_CALL_STACK = NULL;
  cob_cache_free (h_CALL_STACK);
  h_CALL_STACK = NULL;
  call_LOGGER.funcvoid = NULL;
  b_1 = 0;
  cob_cache_free (module);
  module = NULL;

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'RECURSION' */

/* End functions */

