/* Generated by           cobc 2.0.0 */
/* Generated from         recursion.cbl */
/* Generated at           Apr 22 2017 14:58:15 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\recursion.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin recursion.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   5,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,  20,   0, 0x0000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {9, (cob_u8_ptr)"RECURSION", &a_1};
static const cob_field c_2	= {4, (cob_u8_ptr)"INIT", &a_1};
static const cob_field c_3	= {14, (cob_u8_ptr)"RECURSION:INIT", &a_1};
static const cob_field c_4	= {22, (cob_u8_ptr)"Initialized Call Stack", &a_1};
static const cob_field c_5	= {24, (cob_u8_ptr)"CALL-STACK-ADD-PROCEDURE", &a_1};
static const cob_field c_6	= {26, (cob_u8_ptr)"PRINT-CALL-STACK-PROCEDURE", &a_1};
static const cob_field c_7	= {6, (cob_u8_ptr)"ID    ", &a_1};
static const cob_field c_8	= {22, (cob_u8_ptr)"NAME                  ", &a_1};
static const cob_field c_9	= {20, (cob_u8_ptr)"RESULT              ", &a_1};
static const cob_field c_10	= {20, (cob_u8_ptr)"RESULT (NUMERIC)    ", &a_1};
static const cob_field c_11	= {14, (cob_u8_ptr)" RETURN ID    ", &a_1};
static const cob_field c_12	= {1, (cob_u8_ptr)" ", &a_1};
static const cob_field c_13	= {6, (cob_u8_ptr)"DELETE", &a_1};
static const cob_field c_14	= {16, (cob_u8_ptr)"Updating Record:", &a_1};
static const cob_field c_15	= {9, (cob_u8_ptr)"stack.dat", &a_1};

static cob_field cob_all_space	= {1, (cob_u8_ptr)" ", &cob_all_attr};


/* Strings */
static const char st_1[]	= "recursion.cbl";
static const char st_2[]	= "Entry:     RECURSION";
static const char st_3[]	= "Section:   (None)";
static const char st_4[]	= "Paragraph: MAIN-PROCEDURE";
static const char st_5[]	= "MAIN-PROCEDURE";
static const char st_6[]	= "DISPLAY";
static const char st_7[]	= "EVALUATE";
static const char st_8[]	= "MOVE";
static const char st_9[]	= "CALL";
static const char st_10[]	= "GOBACK";
static const char st_11[]	= "Paragraph: RECURSION-PROCEDURE";
static const char st_12[]	= "RECURSION-PROCEDURE";
static const char st_13[]	= "PERFORM";
static const char st_14[]	= "Paragraph: INIT-CALL-STACK-PROCEDURE";
static const char st_15[]	= "INIT-CALL-STACK-PROCEDURE";
static const char st_16[]	= "OPEN";
static const char st_17[]	= "CLOSE";
static const char st_18[]	= "Paragraph: CLOSE-CALL-STACK-PROCEDURE";
static const char st_19[]	= "CLOSE-CALL-STACK-PROCEDURE";
static const char st_20[]	= "DELETE";
static const char st_21[]	= "Paragraph: MOVE-CALL-STACK-TO-WS";
static const char st_22[]	= "MOVE-CALL-STACK-TO-WS";
static const char st_23[]	= "Paragraph: MOVE-WS-TO-CALL-STACK";
static const char st_24[]	= "MOVE-WS-TO-CALL-STACK";
static const char st_25[]	= "Paragraph: CALL-STACK-ADD-PROCEDURE";
static const char st_26[]	= "CALL-STACK-ADD-PROCEDURE";
static const char st_27[]	= "SUBTRACT";
static const char st_28[]	= "STRING";
static const char st_29[]	= "WRITE";
static const char st_30[]	= "ADD";
static const char st_31[]	= "Paragraph: PRINT-CALL-STACK-PROCEDURE";
static const char st_32[]	= "PRINT-CALL-STACK-PROCEDURE";
static const char st_33[]	= "READ";
static const char st_34[]	= "Paragraph: CALL-STACK-DELETE-PROCEDURE";
static const char st_35[]	= "CALL-STACK-DELETE-PROCEDURE";
static const char st_36[]	= "Paragraph: LISP-EVAL-LAST-EXPRESSION";
static const char st_37[]	= "LISP-EVAL-LAST-EXPRESSION";
static const char st_38[]	= "SET";
static const char st_39[]	= "REWRITE";
static const char st_40[]	= "Exit:      RECURSION";

