/* Generated by           cobc 2.0.0 */
/* Generated from         recursion.cbl */
/* Generated at           Apr 22 2017 14:58:15 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\recursion.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin recursion.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"recursion.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 22 2017 14:58:15"
#define  COB_MODULE_DATE		20170422
#define  COB_MODULE_TIME		145815

/* Global variables */
#include "recursion.c.h"

/* Function prototypes */

__declspec(dllexport) int		RECURSION (cob_u8_t *);
static int		RECURSION_ (const int, cob_u8_t *);

/* Functions */

/* PROGRAM-ID 'RECURSION' */

/* ENTRY 'RECURSION' */

int
RECURSION (cob_u8_t *b_36)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
	cob_call_params = 1;
  };

  return RECURSION_ (0, b_36);
}

static int
RECURSION_ (const int entry, cob_u8_t *b_36)
{
  /* Program local variables */
  #include "recursion.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_36 = NULL;
  default:
	break;
  }

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 57        : Entry     RECURSION               : recursion.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 57);
  cob_trace_section (st_3, st_1, 57);

  /* Line: 57        : Paragraph MAIN-PROCEDURE          : recursion.cbl */
  cob_trace_section (st_4, st_1, 57);

  /* Line: 58        : DISPLAY            : recursion.cbl */
  cob_set_location (st_1, 58, NULL, st_5, st_6);
  cob_display (0, 1, 1, &c_1);

  /* Line: 59        : EVALUATE           : recursion.cbl */
  cob_set_location (st_1, 59, NULL, st_5, st_7);

  /* WHEN */

  if (((int)cob_cmp (COB_SET_DATA (f_36, b_36), (cob_field *)&c_2) == 0))
  {

    /* Line: 61        : MOVE               : recursion.cbl */
    cob_set_location (st_1, 61, NULL, st_5, st_8);
    memcpy (b_32, "ADD  ", 5);
    goto l_5;
  }

  /* End EVALUATE */
  l_5:;

  /* Line: 62        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 62, NULL, st_5, st_8);
  cob_move ((cob_field *)&c_3, &f_34);

  /* Line: 64        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 64, NULL, st_5, st_8);
  cob_move ((cob_field *)&c_4, &f_35);

  /* Line: 66        : CALL               : recursion.cbl */
  cob_set_location (st_1, 66, NULL, st_5, st_9);
  cob_procedure_params[0] = &f_32;
  cob_procedure_params[1] = &f_33;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_32, b_33);

  /* Line: 67        : GOBACK             : recursion.cbl */
  cob_set_location (st_1, 67, NULL, st_5, st_10);
  goto exit_program;

  /* Line: 68        : Paragraph RECURSION-PROCEDURE     : recursion.cbl */
  cob_trace_section (st_11, st_1, 68);

  /* Line: 69        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 69, NULL, st_12, st_8);
  cob_check_numeric (&f_26, "WS-CALL-STACK-NEXT-ID");
  memcpy (b_16, b_26, 5);

  /* Line: 70        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 70, NULL, st_12, st_8);
  memcpy (b_16 + 5, b_15, 20);

  /* Line: 71        : PERFORM            : recursion.cbl */
  cob_set_location (st_1, 71, NULL, st_12, st_13);
  /* PERFORM CALL-STACK-ADD-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 11;
  frame_ptr->return_address_ptr = &&l_15;
  goto l_11;
  l_15:
  frame_ptr--;

  /* Line: 72        : Paragraph INIT-CALL-STACK-PROCEDURE: recursion.cbl */
  cob_trace_section (st_14, st_1, 72);

  /* Line: 75        : OPEN               : recursion.cbl */
  cob_set_location (st_1, 75, NULL, st_15, st_16);
  cob_open (h_CALL_STACK, 2, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_1;
    l_16:
    frame_ptr--;
  }

  /* Line: 76        : CLOSE              : recursion.cbl */
  cob_set_location (st_1, 76, NULL, st_15, st_17);
  cob_close (h_CALL_STACK, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_17;
    goto l_1;
    l_17:
    frame_ptr--;
  }

  /* Line: 78        : OPEN               : recursion.cbl */
  cob_set_location (st_1, 78, NULL, st_15, st_16);
  cob_open (h_CALL_STACK, 3, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_18;
    goto l_1;
    l_18:
    frame_ptr--;
  }

  /* Line: 79        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 79, NULL, st_15, st_8);
  memcpy (b_26, "00001", 5);

  /* Line: 80        : Paragraph CLOSE-CALL-STACK-PROCEDURE: recursion.cbl */
  cob_trace_section (st_18, st_1, 80);

  /* Line: 81        : CLOSE              : recursion.cbl */
  cob_set_location (st_1, 81, NULL, st_19, st_17);
  cob_close (h_CALL_STACK, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_1;
    l_19:
    frame_ptr--;
  }

  /* Line: 82        : DELETE             : recursion.cbl */
  cob_set_location (st_1, 82, NULL, st_19, st_20);
  cob_delete_file (h_CALL_STACK, NULL);

  /* Line: 83        : Paragraph MOVE-CALL-STACK-TO-WS   : recursion.cbl */
  cob_trace_section (st_21, st_1, 83);

  /* Line: 84        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 84, NULL, st_22, st_8);
  cob_check_numeric (&f_7, "COMMAND-ID");
  memcpy (b_16, b_14, 5);

  /* Line: 85        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 85, NULL, st_22, st_8);
  memcpy (b_16 + 5, b_14 + 5, 20);

  /* Line: 86        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 86, NULL, st_22, st_8);
  memcpy (b_16 + 25, b_14 + 25, 20);

  /* Line: 88        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 88, NULL, st_22, st_8);
  cob_check_numeric (&f_11, "COMMAND-RETURN-ID");
  memcpy (b_16 + 45, b_14 + 45, 5);

  /* Line: 89        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 89, NULL, st_22, st_8);
  *(b_16 + 70) = *(b_14 + 50);

  /* Line: 90        : Paragraph MOVE-WS-TO-CALL-STACK   : recursion.cbl */
  l_10:;
  cob_trace_section (st_23, st_1, 90);

  /* Line: 91        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 91, NULL, st_24, st_8);
  cob_check_numeric (&f_17, "WS-COMMAND-ID");
  memcpy (b_14, b_16, 5);

  /* Line: 92        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 92, NULL, st_24, st_8);
  memcpy (b_14 + 5, b_16 + 5, 20);

  /* Line: 93        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 93, NULL, st_24, st_8);
  memcpy (b_14 + 25, b_16 + 25, 20);

  /* Line: 95        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 95, NULL, st_24, st_8);
  cob_check_numeric (&f_21, "WS-COMMAND-RETURN-ID");
  memcpy (b_14 + 45, b_16 + 45, 5);

  /* Line: 96        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 96, NULL, st_24, st_8);
  *(b_14 + 50) = *(b_16 + 70);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 97        : Paragraph CALL-STACK-ADD-PROCEDURE: recursion.cbl */
  l_11:;
  cob_trace_section (st_25, st_1, 97);

  /* Line: 98        : MOVE               : recursion.cbl */
  cob_set_location (st_1, 98, NULL, st_26, st_8);
  cob_check_numeric (&f_26, "WS-CALL-STACK-NEXT-ID");
  memcpy (b_16 + 45, b_26, 5);

  /* Line: 99        : SUBTRACT           : recursion.cbl */
  cob_set_location (st_1, 99, NULL, st_26, st_27);
  cob_check_numeric (&f_21, "WS-COMMAND-RETURN-ID");
  cob_sub_int (&f_21, 1, 0);

  /* Line: 100       : PERFORM            : recursion.cbl */
  cob_set_location (st_1, 100, NULL, st_26, st_13);
  /* PERFORM MOVE-WS-TO-CALL-STACK */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 10;
  frame_ptr->return_address_ptr = &&l_20;
  goto l_10;
  l_20:
  frame_ptr--;

  /* Line: 102       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 102, NULL, st_26, st_8);
  cob_move ((cob_field *)&c_5, &f_34);

  /* Line: 103       : STRING             : recursion.cbl */
  cob_set_location (st_1, 103, NULL, st_26, st_28);
  cob_string_init (&f_35, NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_7);
  cob_string_delimited (NULL);
  cob_string_append (&f_8);
  cob_string_finish ();

  /* Line: 108       : WRITE              : recursion.cbl */
  cob_set_location (st_1, 108, NULL, st_26, st_29);
  cob_write (h_CALL_STACK, &f_6, 0, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_21;
    goto l_1;
    l_21:
    frame_ptr--;
  }

  /* Line: 109       : ADD                : recursion.cbl */
  cob_set_location (st_1, 109, NULL, st_26, st_30);
  cob_check_numeric (&f_26, "WS-CALL-STACK-NEXT-ID");
  cob_add_int (&f_26, 1, 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 110       : Paragraph PRINT-CALL-STACK-PROCEDURE: recursion.cbl */
  l_12:;
  cob_trace_section (st_31, st_1, 110);

  /* Line: 111       : DISPLAY            : recursion.cbl */
  cob_set_location (st_1, 111, NULL, st_32, st_6);
  cob_display (0, 1, 1, &c_6);

  /* Line: 112       : DISPLAY            : recursion.cbl */
  cob_set_location (st_1, 112, NULL, st_32, st_6);
  cob_display (0, 1, 5, &c_7, &c_8, &c_9, &c_10, &c_11);

  /* Line: 116       : PERFORM            : recursion.cbl */
  cob_set_location (st_1, 116, NULL, st_32, st_13);
  memcpy (b_14, "00001", 5);
  for (;;)
  {
    if (((int)memcmp (b_14, b_26, 5) == 0))
      break;

    /* Line: 118       : READ               : recursion.cbl */
    cob_set_location (st_1, 118, NULL, st_32, st_33);
    cob_read (h_CALL_STACK, &f_7, NULL, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_22;
      goto l_1;
      l_22:
      frame_ptr--;
    }
    else
    {
      cob_move (&f_14, &f_16);
    }

    /* Line: 121       : DISPLAY            : recursion.cbl */
    cob_set_location (st_1, 121, NULL, st_32, st_6);
    cob_display (0, 1, 13, &f_17, &c_12, &f_18, &c_12, &f_19, &c_12, &f_20, &c_12, &f_21, &c_12, &f_22, &c_12, &f_23);
    cob_add_int (&f_7, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 126       : Paragraph CALL-STACK-DELETE-PROCEDURE: recursion.cbl */
  cob_trace_section (st_34, st_1, 126);

  /* Line: 127       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 127, NULL, st_35, st_8);
  cob_move (&f_6, &f_16);

  /* Line: 128       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 128, NULL, st_35, st_8);
  memcpy (b_29, b_16 + 25, 20);

  /* Line: 129       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 129, NULL, st_35, st_8);
  cob_check_numeric (&f_20, "WS-COMMAND-RESULT-NUMERIC");
  memcpy (b_29 + 20, b_16 + 25, 20);

  /* Line: 131       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 131, NULL, st_35, st_8);
  memcpy (b_33, "CALL-STACK-DELETE-PROCEDURE             ", 40);

  /* Line: 133       : STRING             : recursion.cbl */
  cob_set_location (st_1, 133, NULL, st_35, st_28);
  cob_string_init (&f_35, NULL);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_7);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_8);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_9);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_10);
  cob_string_finish ();

  /* Line: 140       : DISPLAY            : recursion.cbl */
  cob_set_location (st_1, 140, NULL, st_35, st_6);
  cob_display (0, 1, 1, &c_13);

  /* Line: 141       : PERFORM            : recursion.cbl */
  cob_set_location (st_1, 141, NULL, st_35, st_13);
  /* PERFORM PRINT-CALL-STACK-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 12;
  frame_ptr->return_address_ptr = &&l_23;
  goto l_12;
  l_23:
  frame_ptr--;

  /* Line: 142       : DELETE             : recursion.cbl */
  cob_set_location (st_1, 142, NULL, st_35, st_20);
  cob_delete (h_CALL_STACK, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_24;
    goto l_1;
    l_24:
    frame_ptr--;
  }

  /* Line: 143       : READ               : recursion.cbl */
  cob_set_location (st_1, 143, NULL, st_35, st_33);
  cob_read (h_CALL_STACK, &f_11, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_25;
    goto l_1;
    l_25:
    frame_ptr--;
  }
  else
  {
    cob_move (&f_14, &f_16);
  }

  /* Line: 146       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 146, NULL, st_35, st_8);
  cob_move (&f_18, &f_15);

  /* Line: 147       : Paragraph LISP-EVAL-LAST-EXPRESSION: recursion.cbl */
  cob_trace_section (st_36, st_1, 147);

  /* Line: 148       : SET                : recursion.cbl */
  cob_set_location (st_1, 148, NULL, st_37, st_38);
  *(b_27) = 89;

  /* Line: 149       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 149, NULL, st_37, st_8);
  cob_check_numeric (&f_26, "WS-CALL-STACK-NEXT-ID");
  memcpy (b_14, b_26, 5);

  /* Line: 150       : SUBTRACT           : recursion.cbl */
  cob_set_location (st_1, 150, NULL, st_37, st_27);
  cob_check_numeric (&f_7, "COMMAND-ID");
  cob_sub_int (&f_7, 1, 0);

  /* Line: 151       : READ               : recursion.cbl */
  cob_set_location (st_1, 151, NULL, st_37, st_33);
  cob_read (h_CALL_STACK, &f_7, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_26;
    goto l_1;
    l_26:
    frame_ptr--;
  }

  /* Line: 155       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 155, NULL, st_37, st_8);
  memcpy (b_33, "LISP-EVAL-LAST-EXPRESSION               ", 40);

  /* Line: 157       : STRING             : recursion.cbl */
  cob_set_location (st_1, 157, NULL, st_37, st_28);
  cob_string_init (&f_35, NULL);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_7);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_8);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_9);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_10);
  cob_string_finish ();

  /* Line: 165       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 165, NULL, st_37, st_8);
  cob_move (&f_8, &f_15);

  /* Line: 169       : PERFORM            : recursion.cbl */
  cob_set_location (st_1, 169, NULL, st_37, st_13);
  /* PERFORM MOVE-WS-TO-CALL-STACK */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 10;
  frame_ptr->return_address_ptr = &&l_27;
  goto l_10;
  l_27:
  frame_ptr--;

  /* Line: 171       : MOVE               : recursion.cbl */
  cob_set_location (st_1, 171, NULL, st_37, st_8);
  memcpy (b_33, "LISP-EVAL-LAST-EXPRESSION               ", 40);

  /* Line: 173       : STRING             : recursion.cbl */
  cob_set_location (st_1, 173, NULL, st_37, st_28);
  cob_string_init (&f_35, NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_14);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_7);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_8);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_9);
  cob_string_delimited (&cob_all_space);
  cob_string_append (&f_10);
  cob_string_finish ();

  /* Line: 181       : REWRITE            : recursion.cbl */
  cob_set_location (st_1, 181, NULL, st_37, st_39);
  cob_rewrite (h_CALL_STACK, &f_6, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_1;
    l_28:
    frame_ptr--;
  }

  /* Line: 184       : SET                : recursion.cbl */
  cob_set_location (st_1, 184, NULL, st_37, st_38);
  *(b_27) = 78;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_40, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;


  /* Paragraph Default Error Handler   */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  /* Initialize module structure */
  module->module_name = "RECURSION";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())RECURSION;
  module->module_cancel.funcptr = (void *(*)())RECURSION_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_15, 32, 100);
  memset (b_16, 48, 5);
  memset (b_16 + 5, 32, 40);
  memset (b_16 + 45, 48, 5);
  memset (b_16 + 50, 32, 21);
  *(cob_u8_ptr)(b_25) = 32;
  memset (b_26, 48, 5);
  *(cob_u8_ptr)(b_27) = 32;
  memset (b_29, 32, 20);
  memset (b_29 + 20, 48, 20);
  memset (b_32, 32, 5);
  memset (b_33, 32, 140);


  if (!h_CALL_STACK)
  {
    h_CALL_STACK = cob_cache_malloc (sizeof(cob_file));
  }
  if (!k_CALL_STACK)
  {
    k_CALL_STACK = cob_cache_malloc (sizeof (cob_file_key) * 1);
  }
  k_CALL_STACK->field = &f_7;
  k_CALL_STACK->flag = 0;
  k_CALL_STACK->offset = 0;
  h_CALL_STACK->select_name = (const char *)"CALL-STACK";
  h_CALL_STACK->file_status = h_CALL_STACK_status;
  memset (h_CALL_STACK_status, '0', 2);
  h_CALL_STACK->assign = (cob_field *)&c_15;
  h_CALL_STACK->record = &f_14;
  h_CALL_STACK->variable_record = NULL;
  h_CALL_STACK->record_min = 51;
  h_CALL_STACK->record_max = 51;
  h_CALL_STACK->nkeys = 1;
  h_CALL_STACK->keys = k_CALL_STACK;
  h_CALL_STACK->file = NULL;
  h_CALL_STACK->fd = -1;
  h_CALL_STACK->organization = 3;
  h_CALL_STACK->access_mode = 3;
  h_CALL_STACK->lock_mode = 0;
  h_CALL_STACK->open_mode = 0;
  h_CALL_STACK->flag_optional = 1;
  h_CALL_STACK->last_open_mode = 0;
  h_CALL_STACK->flag_operation = 0;
  h_CALL_STACK->flag_nonexistent = 0;
  h_CALL_STACK->flag_end_of_file = 0;
  h_CALL_STACK->flag_begin_of_file = 0;
  h_CALL_STACK->flag_first_read = 0;
  h_CALL_STACK->flag_read_done = 0;
  h_CALL_STACK->flag_select_features = 0;
  h_CALL_STACK->flag_needs_nl = 0;
  h_CALL_STACK->flag_needs_top = 0;
  h_CALL_STACK->file_version = 1;

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  cob_close (h_CALL_STACK, NULL, COB_CLOSE_NORMAL, 1);
  cob_cache_free (k_CALL_STACK);
  k_CALL_STACK = NULL;
  cob_cache_free (h_CALL_STACK);
  h_CALL_STACK = NULL;
  call_LOGGER.funcvoid = NULL;
  b_1 = 0;
  cob_cache_free (module);
  module = NULL;

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'RECURSION' */

/* End functions */

