/* Generated by           cobc 2.0.0 */
/* Generated from         recursion.cbl */
/* Generated at           Apr 22 2017 20:44:10 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\recursion.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin recursion.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   5,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,  20,   0, 0x0000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {4, (cob_u8_ptr)"INIT", &a_1};
static const cob_field c_2	= {17, (cob_u8_ptr)"ADD-TO-CALL-STACK", &a_1};
static const cob_field c_3	= {4, (cob_u8_ptr)"PEEK", &a_1};
static const cob_field c_4	= {14, (cob_u8_ptr)"POP-CALL-STACK", &a_1};
static const cob_field c_5	= {8, (cob_u8_ptr)"IS-EMPTY", &a_1};
static const cob_field c_6	= {5, (cob_u8_ptr)"PRINT", &a_1};
static const cob_field c_7	= {5, (cob_u8_ptr)"CLOSE", &a_1};
static const cob_field c_8	= {14, (cob_u8_ptr)"RECURSION:INIT", &a_1};
static const cob_field c_9	= {22, (cob_u8_ptr)"Initialized Call Stack", &a_1};
static const cob_field c_10	= {24, (cob_u8_ptr)"RECURSION:POP-CALL-STACK", &a_1};
static const cob_field c_11	= {22, (cob_u8_ptr)"Closed call-stack file", &a_1};
static const cob_field c_12	= {26, (cob_u8_ptr)"PRINT-CALL-STACK-PROCEDURE", &a_1};
static const cob_field c_13	= {6, (cob_u8_ptr)"ID    ", &a_1};
static const cob_field c_14	= {22, (cob_u8_ptr)"NAME                  ", &a_1};
static const cob_field c_15	= {20, (cob_u8_ptr)"RESULT              ", &a_1};
static const cob_field c_16	= {20, (cob_u8_ptr)"RESULT (NUMERIC)    ", &a_1};
static const cob_field c_17	= {14, (cob_u8_ptr)" RETURN ID    ", &a_1};
static const cob_field c_18	= {7, (cob_u8_ptr)"DELETED", &a_1};
static const cob_field c_19	= {1, (cob_u8_ptr)" ", &a_1};
static const cob_field c_20	= {11, (cob_u8_ptr)"STACK-EMPTY", &a_1};
static const cob_field c_21	= {9, (cob_u8_ptr)"NOT-EMPTY", &a_1};
static const cob_field c_22	= {16, (cob_u8_ptr)"Updating Record:", &a_1};
static const cob_field c_23	= {9, (cob_u8_ptr)"stack.dat", &a_1};

static cob_field cob_all_space	= {1, (cob_u8_ptr)" ", &cob_all_attr};


/* Strings */
static const char st_1[]	= "recursion.cbl";
static const char st_2[]	= "Entry:     RECURSION";
static const char st_3[]	= "Section:   (None)";
static const char st_4[]	= "Paragraph: MAIN-PROCEDURE";
static const char st_5[]	= "MAIN-PROCEDURE";
static const char st_6[]	= "EVALUATE";
static const char st_7[]	= "PERFORM";
static const char st_8[]	= "GOBACK";
static const char st_9[]	= "Paragraph: LOG-INIT-CALL-STACK";
static const char st_10[]	= "LOG-INIT-CALL-STACK";
static const char st_11[]	= "MOVE";
static const char st_12[]	= "CALL";
static const char st_13[]	= "Paragraph: LOG-ADD-TO-CALL-STACK";
static const char st_14[]	= "LOG-ADD-TO-CALL-STACK";
static const char st_15[]	= "STRING";
static const char st_16[]	= "Paragraph: LOG-PEEK-CALL-STACK";
static const char st_17[]	= "LOG-PEEK-CALL-STACK";
static const char st_18[]	= "Paragraph: LOG-POP-FROM-CALL-STACK";
static const char st_19[]	= "LOG-POP-FROM-CALL-STACK";
static const char st_20[]	= "Paragraph: LOG-IS-EMPTY-CALL-STACK";
static const char st_21[]	= "LOG-IS-EMPTY-CALL-STACK";
static const char st_22[]	= "Paragraph: LOG-CLOSE-CALL-STACK";
static const char st_23[]	= "LOG-CLOSE-CALL-STACK";
static const char st_24[]	= "Paragraph: LOG-DELETE-FROM-CALL-STACK";
static const char st_25[]	= "LOG-DELETE-FROM-CALL-STACK";
static const char st_26[]	= "Paragraph: INIT-CALL-STACK-PROCEDURE";
static const char st_27[]	= "INIT-CALL-STACK-PROCEDURE";
static const char st_28[]	= "OPEN";
static const char st_29[]	= "CLOSE";
static const char st_30[]	= "SET";
static const char st_31[]	= "Paragraph: CLOSE-CALL-STACK-PROCEDURE";
static const char st_32[]	= "CLOSE-CALL-STACK-PROCEDURE";
static const char st_33[]	= "DELETE";
static const char st_34[]	= "Paragraph: CALL-STACK-ADD-PROCEDURE";
static const char st_35[]	= "CALL-STACK-ADD-PROCEDURE";
static const char st_36[]	= "SUBTRACT";
static const char st_37[]	= "WRITE";
static const char st_38[]	= "IF";
static const char st_39[]	= "ADD";
static const char st_40[]	= "Paragraph: PRINT-CALL-STACK-PROCEDURE";
static const char st_41[]	= "PRINT-CALL-STACK-PROCEDURE";
static const char st_42[]	= "DISPLAY";
static const char st_43[]	= "READ";
static const char st_44[]	= "Paragraph: CALL-STACK-GET-TOP-PROCEDURE";
static const char st_45[]	= "CALL-STACK-GET-TOP-PROCEDURE";
static const char st_46[]	= "Paragraph: POP-CALL-STACK-PROCEDURE";
static const char st_47[]	= "POP-CALL-STACK-PROCEDURE";
static const char st_48[]	= "Paragraph: IS-STACK-EMPTY-PROCEDURE";
static const char st_49[]	= "IS-STACK-EMPTY-PROCEDURE";
static const char st_50[]	= "Paragraph: CALL-STACK-DELETE-PROCEDURE";
static const char st_51[]	= "CALL-STACK-DELETE-PROCEDURE";
static const char st_52[]	= "Paragraph: RECURSION-PROCEDURE";
static const char st_53[]	= "RECURSION-PROCEDURE";
static const char st_54[]	= "Paragraph: MOVE-CALL-STACK-TO-WS";
static const char st_55[]	= "MOVE-CALL-STACK-TO-WS";
static const char st_56[]	= "Paragraph: MOVE-WS-TO-CALL-STACK";
static const char st_57[]	= "MOVE-WS-TO-CALL-STACK";
static const char st_58[]	= "Paragraph: LISP-EVAL-LAST-EXPRESSION";
static const char st_59[]	= "LISP-EVAL-LAST-EXPRESSION";
static const char st_60[]	= "REWRITE";
static const char st_61[]	= "Exit:      RECURSION";

