/* Generated by           cobc 2.0.0 */
/* Generated from         TOKENIZER.cbl */
/* Generated at           Apr 22 2017 12:40:05 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\TOKENIZER.exe -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin TOKENIZER.cbl */

/* Program local variables for 'TOKENIZER' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File LISP-FILE */
static cob_file		*h_LISP_FILE = NULL;
static unsigned char	h_LISP_FILE_status[4];

/* Call pointers */
static cob_call_union	call_LOGGER;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_7[2000] __attribute__((aligned));	/* LISP-FILE Record */
static cob_u8_t	b_8[30] __attribute__((aligned));	/* WS-LISP-NAME */
static cob_u8_t	b_9[2000] __attribute__((aligned));	/* WS-IN-LISP-RECORD */
static cob_u8_t	b_12[10] __attribute__((aligned));	/* WS-LISP-LENGTH */
static cob_u8_t	b_13[2023] __attribute__((aligned));	/* WS-FORMAT-LISP */
static cob_u8_t	b_22[50001] __attribute__((aligned));	/* WS-LISP-SYMBOLS */
static cob_u8_t	b_25[10] __attribute__((aligned));	/* WS-FORMAT-STR-INDEX */
static cob_u8_t	b_26[10] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_27[10] __attribute__((aligned));	/* STRING-PTR */
static cob_u8_t	b_28[10] __attribute__((aligned));	/* WS-TEMP-NUM */
static cob_u8_t	b_29[1] __attribute__((aligned));	/* WS-FLAG */
static cob_u8_t	b_31[2] __attribute__((aligned));	/* WS-SYMBOL-FLAGS */
static cob_u8_t	b_36[22] __attribute__((aligned));	/* WS-PARSE-STR */
static cob_u8_t	b_44[5] __attribute__((aligned));	/* WS-LOG-OPERATION-FLAG */
static cob_u8_t	b_45[140] __attribute__((aligned));	/* WS-LOG-RECORD */

/* End of data storage */


/* Fields */
static cob_field f_7	= {2000, b_7, &a_1};	/* LISP-FILE Record */
static cob_field f_8	= {30, b_8, &a_1};	/* WS-LISP-NAME */
static cob_field f_9	= {2000, b_9, &a_1};	/* WS-IN-LISP-RECORD */
static cob_field f_12	= {10, b_12, &a_3};	/* WS-LISP-LENGTH */
static cob_field f_14	= {10, b_13, &a_3};	/* WS-NUM-LENGTH-ADD */
static cob_field f_20	= {10, b_13 + 2012, &a_3};	/* WS-PAREN-TEMP-NUM */
static cob_field f_21	= {1, b_13 + 2022, &a_1};	/* WS-WHICH-PAREN */
static cob_field f_23	= {1, b_22, &a_4};	/* WS-SYMBOL-TABLE-SIZE */
static cob_field f_25	= {10, b_25, &a_3};	/* WS-FORMAT-STR-INDEX */
static cob_field f_26	= {10, b_26, &a_3};	/* WS-COUNT */
static cob_field f_27	= {10, b_27, &a_3};	/* STRING-PTR */
static cob_field f_29	= {1, b_29, &a_1};	/* WS-FLAG */
static cob_field f_32	= {1, b_31, &a_1};	/* WS-OPEN-PAREN */
static cob_field f_34	= {1, b_31 + 1, &a_1};	/* WS-CLOSE-PAREN */
static cob_field f_37	= {5, b_36, &a_5};	/* WS-PARSE-STR-INDEX */
static cob_field f_40	= {1, b_36 + 6, &a_1};	/* WS-PARSE-STR-CHAR */
static cob_field f_41	= {5, b_36 + 7, &a_5};	/* WS-PARSE-EXPRESSION-START */
static cob_field f_42	= {5, b_36 + 12, &a_5};	/* WS-PARSE-EXPRESSION-END */
static cob_field f_43	= {5, b_36 + 17, &a_5};	/* WS-PARSE-EXPRESSION-LEN */
static cob_field f_44	= {5, b_44, &a_1};	/* WS-LOG-OPERATION-FLAG */
static cob_field f_45	= {140, b_45, &a_2};	/* WS-LOG-RECORD */
static cob_field f_47	= {100, b_45 + 40, &a_1};	/* WS-LOG-RECORD-MESSAGE */

/* End of fields */

