/* Generated by           cobc 2.0.0 */
/* Generated from         tokenizer.cbl */
/* Generated at           Apr 22 2017 21:52:03 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\tokenizer.dll -std=default -Wall -debug -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin tokenizer.cbl */

/* Program local variables for 'TOKENIZER' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File LISP-FILE */
static cob_file		*h_LISP_FILE = NULL;
static unsigned char	h_LISP_FILE_status[4];

/* Call pointers */
static cob_call_union	call_LOGGER;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_7[2000] __attribute__((aligned));	/* LISP-FILE Record */
static cob_u8_t	b_8[30] __attribute__((aligned));	/* WS-LISP-NAME */
static cob_u8_t	b_9[2000] __attribute__((aligned));	/* WS-IN-LISP-RECORD */
static cob_u8_t	b_11[10] __attribute__((aligned));	/* WS-LISP-LENGTH */
static cob_u8_t	b_12[2023] __attribute__((aligned));	/* WS-FORMAT-LISP */
static cob_u8_t	b_21[10] __attribute__((aligned));	/* WS-FORMAT-STR-INDEX */
static cob_u8_t	b_22[10] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_23[10] __attribute__((aligned));	/* STRING-PTR */
static cob_u8_t	b_24[10] __attribute__((aligned));	/* WS-TEMP-NUM */
static cob_u8_t	b_25[1] __attribute__((aligned));	/* WS-FLAG */
static cob_u8_t	b_27[2] __attribute__((aligned));	/* WS-SYMBOL-FLAGS */
static cob_u8_t	b_32[22] __attribute__((aligned));	/* WS-PARSE-STR */
static cob_u8_t	b_40[5] __attribute__((aligned));	/* WS-LOG-OPERATION-FLAG */
static cob_u8_t	b_41[140] __attribute__((aligned));	/* WS-LOG-RECORD */

/* End of data storage */


/* Fields */
static cob_field f_7	= {2000, b_7, &a_4};	/* LISP-FILE Record */
static cob_field f_8	= {30, b_8, &a_4};	/* WS-LISP-NAME */
static cob_field f_9	= {2000, b_9, &a_4};	/* WS-IN-LISP-RECORD */
static cob_field f_11	= {10, b_11, &a_2};	/* WS-LISP-LENGTH */
static cob_field f_13	= {10, b_12, &a_2};	/* WS-NUM-LENGTH-ADD */
static cob_field f_19	= {10, b_12 + 2012, &a_2};	/* WS-PAREN-TEMP-NUM */
static cob_field f_20	= {1, b_12 + 2022, &a_4};	/* WS-WHICH-PAREN */
static cob_field f_21	= {10, b_21, &a_2};	/* WS-FORMAT-STR-INDEX */
static cob_field f_22	= {10, b_22, &a_2};	/* WS-COUNT */
static cob_field f_23	= {10, b_23, &a_2};	/* STRING-PTR */
static cob_field f_25	= {1, b_25, &a_4};	/* WS-FLAG */
static cob_field f_28	= {1, b_27, &a_4};	/* WS-OPEN-PAREN */
static cob_field f_30	= {1, b_27 + 1, &a_4};	/* WS-CLOSE-PAREN */
static cob_field f_33	= {5, b_32, &a_1};	/* WS-PARSE-STR-INDEX */
static cob_field f_37	= {5, b_32 + 7, &a_1};	/* WS-PARSE-EXPRESSION-START */
static cob_field f_38	= {5, b_32 + 12, &a_1};	/* WS-PARSE-EXPRESSION-END */
static cob_field f_39	= {5, b_32 + 17, &a_1};	/* WS-PARSE-EXPRESSION-LEN */
static cob_field f_40	= {5, b_40, &a_4};	/* WS-LOG-OPERATION-FLAG */
static cob_field f_41	= {140, b_41, &a_5};	/* WS-LOG-RECORD */
static cob_field f_43	= {100, b_41 + 40, &a_4};	/* WS-LOG-RECORD-MESSAGE */
static cob_field f_46	= {4, NULL, &a_6};	/* LS-SYMBOL-TABLE-SIZE */

/* End of fields */

