/* Generated by           cobc 2.0.0 */
/* Generated from         tokenizer.cbl */
/* Generated at           Apr 27 2017 17:51:31 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -o bin\tokenizer.dll -std=default -Wall -g -LC:\Users\laury\Documents\Computer School\Recurse Center\Cisp\subroutines\bin -L\subroutines\bin -L..\subroutines\bin tokenizer.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"tokenizer.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 27 2017 17:51:31"
#define  COB_MODULE_DATE		20170427
#define  COB_MODULE_TIME		175131

/* Global variables */
#include "tokenizer.c.h"

/* Function prototypes */

__declspec(dllexport) int		TOKENIZER (cob_u8_t *, cob_u8_t *, cob_u8_t *);
static int		TOKENIZER_ (const int, cob_u8_t *, cob_u8_t *, cob_u8_t *);

/* Functions */

/* PROGRAM-ID 'TOKENIZER' */

/* ENTRY 'TOKENIZER' */

int
TOKENIZER (cob_u8_t *b_48, cob_u8_t *b_49, cob_u8_t *b_50)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
	cob_call_params = 3;
  };

  return TOKENIZER_ (0, b_48, b_49, b_50);
}

static int
TOKENIZER_ (const int entry, cob_u8_t *b_48, cob_u8_t *b_49, 
	cob_u8_t *b_50)
{
  /* Program local variables */
  #include "tokenizer.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_48 = NULL;
  case 1:
  	b_49 = NULL;
  case 2:
  	b_50 = NULL;
  default:
	break;
  }

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 72        : Entry     TOKENIZER               : tokenizer.cbl */
  l_2:;

  /* Line: 72        : Paragraph MAIN-PROCEDURE          : tokenizer.cbl */

  /* Line: 75        : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 75, NULL, st_2, st_3);
  /* PERFORM FILE-HANDLING-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_21;
  goto l_8;
  l_21:
  frame_ptr--;

  /* Line: 78        : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 78, NULL, st_2, st_3);
  /* PERFORM TOKENIZE-LISP-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 9;
  frame_ptr->return_address_ptr = &&l_22;
  goto l_9;
  l_22:
  frame_ptr--;

  /* Line: 79        : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 79, NULL, st_2, st_3);
  /* PERFORM CAL-LENGTH-ALL-SYMBOLS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_23;
  goto l_5;
  l_23:
  frame_ptr--;

  /* Line: 81        : GOBACK             : tokenizer.cbl */
  cob_set_location (st_1, 81, NULL, st_2, st_4);
  goto exit_program;

  /* Line: 82        : Paragraph CAL-LENGTH-ALL-SYMBOLS  : tokenizer.cbl */
  l_5:;

  /* Line: 83        : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 83, NULL, st_5, st_3);
  memcpy (b_26, "0000000001", 10);
  for (;;)
  {
    if (((int)cob_cmp_numdisp (b_26, 10, 100LL, 0) == 0))
      break;

    /* Line: 84        : PERFORM            : tokenizer.cbl */
    cob_set_location (st_1, 84, NULL, st_5, st_3);
    /* PERFORM CALC-LENGTH-SYMBOL */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_24;
    goto l_6;
    l_24:
    frame_ptr--;

    /* Line: 85        : MOVE               : tokenizer.cbl */
    cob_set_location (st_1, 85, NULL, st_5, st_6);
    cob_move (&f_43, COB_SET_FLD(f0, 2, b_50 + 5004 + 2 * (cob_get_int (&f_26) - 1), &a_3));
    cob_add_int (&f_26, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 87        : Paragraph CALC-LENGTH-SYMBOL      : tokenizer.cbl */
  l_6:;

  /* Line: 88        : SET                : tokenizer.cbl */
  cob_set_location (st_1, 88, NULL, st_7, st_8);
  *(b_36 + 5) = 78;

  /* Line: 89        : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 89, NULL, st_7, st_6);
  memset (b_36 + 17, 48, 5);

  /* Line: 90        : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 90, NULL, st_7, st_3);
  memcpy (b_36, "00001", 5);
  for (;;)
  {
    if ((((int)(int)(*(b_36 + 5) - 89) == 0) || 
        ((int)cob_cmp_numdisp (b_36, 5, 100LL, 0) > 0)))
      break;

    /* Line: 92        : IF                 : tokenizer.cbl */
    cob_set_location (st_1, 92, NULL, st_7, st_9);
    if (((int)(int)(*(b_50 + 4 + 50 * (cob_get_int (&f_26) - 1) + (cob_get_numdisp (b_36, 5) - 1)) - 32) == 0))
    {

      /* Line: 93        : SET                : tokenizer.cbl */
      cob_set_location (st_1, 93, NULL, st_7, st_8);
      *(b_36 + 5) = 89;
    }
    else
    {
      /* ELSE */

      /* Line: 95        : ADD                : tokenizer.cbl */
      cob_set_location (st_1, 95, NULL, st_7, st_10);
      cob_add_int (&f_43, 1, 0);
    }
    cob_add_int (&f_37, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 98        : Paragraph APPEND-LISP-PROCEDURE   : tokenizer.cbl */
  l_7:;

  /* Line: 101       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 101, NULL, st_11, st_6);
  memcpy (b_13, b_7, 200);

  /* Line: 102       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 102, NULL, st_11, st_3);
  /* PERFORM CALC-LISP-LENGTH */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 13;
  frame_ptr->return_address_ptr = &&l_25;
  goto l_13;
  l_25:
  frame_ptr--;

  /* Line: 103       : IF                 : tokenizer.cbl */
  cob_set_location (st_1, 103, NULL, st_11, st_9);
  if (!((int)(int)(*(b_14) - 89) == 0))
  {

    /* Line: 104       : IF                 : tokenizer.cbl */
    cob_set_location (st_1, 104, NULL, st_11, st_9);
    if (((int)cob_cmp_numdisp (b_28, 10, 0LL, 0) == 0))
    {

      /* Line: 105       : MOVE               : tokenizer.cbl */
      cob_set_location (st_1, 105, NULL, st_11, st_6);
      memcpy (b_9, b_7, 200);
    }
    else
    {
      /* ELSE */

      /* Line: 107       : ADD                : tokenizer.cbl */
      cob_set_location (st_1, 107, NULL, st_11, st_10);
      cob_add_int (&f_28, 1, 0);

      /* Line: 108       : STRING             : tokenizer.cbl */
      cob_set_location (st_1, 108, NULL, st_11, st_12);
      cob_string_init (&f_9, NULL);
      cob_string_delimited (NULL);
      cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_28), b_9 + 0, &a_4));
      cob_string_delimited (NULL);
      cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_12), b_7 + 0, &a_4));
      cob_string_finish ();

      /* Line: 112       : SUBTRACT           : tokenizer.cbl */
      cob_set_location (st_1, 112, NULL, st_11, st_13);
      cob_sub_int (&f_28, 1, 0);
    }

    /* Line: 114       : ADD                : tokenizer.cbl */
    cob_set_location (st_1, 114, NULL, st_11, st_10);
    cob_add (&f_28, &f_12, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 116       : Paragraph FILE-HANDLING-PROCEDURE : tokenizer.cbl */
  l_8:;

  /* Line: 118       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 118, NULL, st_14, st_6);
  memmove (b_8, b_48, 100);

  /* Line: 119       : OPEN               : tokenizer.cbl */
  cob_set_location (st_1, 119, NULL, st_14, st_15);
  cob_open (h_LISP_FILE, 1, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_26;
    goto l_1;
    l_26:
    frame_ptr--;
  }

  /* Line: 120       : READ               : tokenizer.cbl */
  cob_set_location (st_1, 120, NULL, st_14, st_16);
  cob_read_next (h_LISP_FILE, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {

      /* Line: 121       : MOVE               : tokenizer.cbl */
      cob_set_location (st_1, 121, NULL, st_14, st_6);
      *(b_10) = 89;
    }
    else
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_27;
      goto l_1;
      l_27:
      frame_ptr--;
    }
  }
  else
  {

    /* Line: 123       : MOVE               : tokenizer.cbl */
    cob_set_location (st_1, 123, NULL, st_14, st_6);
    memcpy (b_13, b_7, 200);

    /* Line: 124       : PERFORM            : tokenizer.cbl */
    cob_set_location (st_1, 124, NULL, st_14, st_3);
    /* PERFORM CALC-LISP-LENGTH */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 13;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_13;
    l_28:
    frame_ptr--;

    /* Line: 125       : IF                 : tokenizer.cbl */
    cob_set_location (st_1, 125, NULL, st_14, st_9);
    if (!((int)(int)(*(b_14) - 89) == 0))
    {

      /* Line: 126       : MOVE               : tokenizer.cbl */
      cob_set_location (st_1, 126, NULL, st_14, st_6);
      memcpy (b_9, b_7, 200);

      /* Line: 127       : MOVE               : tokenizer.cbl */
      cob_set_location (st_1, 127, NULL, st_14, st_6);
      memcpy (b_28, b_12, 10);
    }
  }

  /* Line: 130       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 130, NULL, st_14, st_3);
  for (;;)
  {
    if (((int)(int)(*(b_10) - 89) == 0))
      break;

    /* Line: 131       : READ               : tokenizer.cbl */
    cob_set_location (st_1, 131, NULL, st_14, st_16);
    cob_read_next (h_LISP_FILE, NULL, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {

        /* Line: 132       : MOVE               : tokenizer.cbl */
        cob_set_location (st_1, 132, NULL, st_14, st_6);
        *(b_10) = 89;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_29;
        goto l_1;
        l_29:
        frame_ptr--;
      }
    }
    else
    {

      /* Line: 133       : PERFORM            : tokenizer.cbl */
      cob_set_location (st_1, 133, NULL, st_14, st_3);
      /* PERFORM APPEND-LISP-PROCEDURE */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 7;
      frame_ptr->return_address_ptr = &&l_30;
      goto l_7;
      l_30:
      frame_ptr--;
    }
  }

  /* Line: 136       : CLOSE              : tokenizer.cbl */
  cob_set_location (st_1, 136, NULL, st_14, st_17);
  cob_close (h_LISP_FILE, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_31;
    goto l_1;
    l_31:
    frame_ptr--;
  }

  /* Line: 138       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 138, NULL, st_14, st_6);
  memcpy (b_44, "ADD  ", 5);

  /* Line: 139       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 139, NULL, st_14, st_6);
  memcpy (b_45, "TOKENIZER:FILE-HANDLING-PROCEDURE       ", 40);

  /* Line: 141       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 141, NULL, st_14, st_6);
  cob_move ((cob_field *)&c_1, &f_47);

  /* Line: 142       : CALL               : tokenizer.cbl */
  cob_set_location (st_1, 142, NULL, st_14, st_18);
  cob_procedure_params[0] = &f_44;
  cob_procedure_params[1] = &f_45;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_44, b_45);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 143       : Paragraph TOKENIZE-LISP-PROCEDURE : tokenizer.cbl */
  l_9:;

  /* Line: 145       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 145, NULL, st_19, st_3);
  /* PERFORM FORMAT-LISP-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 11;
  frame_ptr->return_address_ptr = &&l_32;
  goto l_11;
  l_32:
  frame_ptr--;

  /* Line: 148       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 148, NULL, st_19, st_6);
  memcpy (b_27, "0000000001", 10);

  /* Line: 149       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 149, NULL, st_19, st_6);
  memset (b_50, 48, 4);

  /* Line: 150       : SET                : tokenizer.cbl */
  cob_set_location (st_1, 150, NULL, st_19, st_8);
  *(b_29) = 78;

  /* Line: 151       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 151, NULL, st_19, st_3);
  memcpy (b_26, "0000000001", 10);
  for (;;)
  {
    if ((((int)cob_cmp_numdisp (b_26, 10, 100LL, 0) == 0) || 
        ((int)cob_cmp (&f_26, &f_29) == 0)))
      break;

    /* Line: 153       : UNSTRING           : tokenizer.cbl */
    cob_set_location (st_1, 153, NULL, st_19, st_20);
    cob_unstring_init (&f_9, &f_27, 1);
    cob_unstring_delimited ((cob_field *)&c_2, 1);
    cob_unstring_into (COB_SET_FLD(f0, 50, b_50 + 4 + 50 * (cob_get_int (&f_26) - 1), &a_4), 0, 0);
    cob_unstring_finish ();

    /* Line: 155       : IF                 : tokenizer.cbl */
    cob_set_location (st_1, 155, NULL, st_19, st_9);
    if (((int)cob_cmp (COB_SET_FLD(f0, 50, b_50 + 4 + 50 * (cob_get_int (&f_26) - 1), &a_4), &cob_all_space) == 0))
    {

      /* Line: 156       : SET                : tokenizer.cbl */
      cob_set_location (st_1, 156, NULL, st_19, st_8);
      *(b_29) = 89;
    }
    else
    {
      /* ELSE */

      /* Line: 158       : ADD                : tokenizer.cbl */
      cob_set_location (st_1, 158, NULL, st_19, st_10);
      cob_add_int (COB_SET_DATA (f_51, b_50), 1, 0);
    }
    cob_add_int (&f_26, 1, 0);
  }

  /* Line: 162       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 162, NULL, st_19, st_6);
  memcpy (b_44, "ADD  ", 5);

  /* Line: 163       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 163, NULL, st_19, st_6);
  memcpy (b_45, "TOKENIZER:TOKENIZE-LISP-PROCEDURE       ", 40);

  /* Line: 165       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 165, NULL, st_19, st_6);
  cob_move ((cob_field *)&c_3, &f_47);

  /* Line: 166       : CALL               : tokenizer.cbl */
  cob_set_location (st_1, 166, NULL, st_19, st_18);
  cob_procedure_params[0] = &f_44;
  cob_procedure_params[1] = &f_45;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_44, b_45);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 167       : Paragraph PRINT-SYMBOL-TABLE      : tokenizer.cbl */

  /* Line: 169       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 169, NULL, st_21, st_6);
  memcpy (b_26, "0000000001", 10);

  /* Line: 170       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 170, NULL, st_21, st_3);
  memcpy (b_26, "0000000001", 10);
  for (;;)
  {
    if (((int)cob_cmp_numdisp (b_26, 10, cob_get_llint (COB_SET_DATA (f_51, b_50)), 0) > 0))
      break;

    /* Line: 172       : DISPLAY            : tokenizer.cbl */
    cob_set_location (st_1, 172, NULL, st_21, st_22);
    cob_display (0, 1, 1, &f_26);

    /* Line: 173       : DISPLAY            : tokenizer.cbl */
    cob_set_location (st_1, 173, NULL, st_21, st_22);
    cob_display (0, 1, 1, COB_SET_FLD(f0, 50, b_50 + 4 + 50 * (cob_get_int (&f_26) - 1), &a_4));

    /* Line: 174       : DISPLAY            : tokenizer.cbl */
    cob_set_location (st_1, 174, NULL, st_21, st_22);
    cob_display (0, 1, 1, COB_SET_FLD(f0, 2, b_50 + 5004 + 2 * (cob_get_int (&f_26) - 1), &a_3));
    cob_add_int (&f_26, 1, 0);
  }

  /* Line: 176       : Paragraph FORMAT-LISP-PROCEDURE   : tokenizer.cbl */
  l_11:;

  /* Line: 181       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 181, NULL, st_23, st_6);
  memcpy (b_13, b_9, 200);

  /* Line: 182       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 182, NULL, st_23, st_3);
  /* PERFORM CALC-LISP-LENGTH */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 13;
  frame_ptr->return_address_ptr = &&l_33;
  goto l_13;
  l_33:
  frame_ptr--;

  /* Line: 183       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 183, NULL, st_23, st_6);
  memcpy (b_25, "0000000001", 10);

  /* Line: 184       : IF                 : tokenizer.cbl */
  cob_set_location (st_1, 184, NULL, st_23, st_9);
  if ((((int)(int)(*(b_9 + 0) - 40) == 0) && 
      !((int)(int)(*(b_9 + 1) - 32) == 0)))
  {

    /* Line: 186       : MOVE               : tokenizer.cbl */
    cob_set_location (st_1, 186, NULL, st_23, st_6);
    cob_move (&f_9, &f_22);

    /* Line: 187       : STRING             : tokenizer.cbl */
    cob_set_location (st_1, 187, NULL, st_23, st_12);
    cob_string_init (&f_9, NULL);
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_4);
    cob_string_delimited (NULL);
    cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_12), b_16 + 12 + 1, &a_4));
    cob_string_finish ();

    /* Line: 190       : ADD                : tokenizer.cbl */
    cob_set_location (st_1, 190, NULL, st_23, st_10);
    cob_add_int (&f_25, 3, 0);

    /* Line: 191       : ADD                : tokenizer.cbl */
    cob_set_location (st_1, 191, NULL, st_23, st_10);
    cob_add_int (&f_12, 1, 0);
  }

  /* Line: 193       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 193, NULL, st_23, st_3);
  memmove (b_25, b_25, 10);
  for (;;)
  {
    if (((int)memcmp (b_25, b_12, 10) > 0))
      break;

    /* Line: 195       : SET                : tokenizer.cbl */
    cob_set_location (st_1, 195, NULL, st_23, st_8);
    *(b_16 + 11) = 78;

    /* Line: 196       : SET                : tokenizer.cbl */
    cob_set_location (st_1, 196, NULL, st_23, st_8);
    *(b_16 + 10) = 78;

    /* Line: 197       : MOVE               : tokenizer.cbl */
    cob_set_location (st_1, 197, NULL, st_23, st_6);
    cob_move (&f_9, &f_22);

    /* Line: 198       : EVALUATE           : tokenizer.cbl */
    cob_set_location (st_1, 198, NULL, st_23, st_24);

    /* WHEN */

    if (((int)(int)(*(b_9 + (cob_get_int (&f_25) - 1)) - 40) == 0))
    {

      /* Line: 200       : PERFORM            : tokenizer.cbl */
      cob_set_location (st_1, 200, NULL, st_23, st_3);
      /* PERFORM FORMAT-PAREN-SPACE-PROCEDURE */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 20;
      frame_ptr->return_address_ptr = &&l_34;
      goto l_20;
      l_34:
      frame_ptr--;
      goto l_12;
    }

    /* WHEN */

    if (((int)(int)(*(b_9 + (cob_get_int (&f_25) - 1)) - 41) == 0))
    {

      /* Line: 202       : PERFORM            : tokenizer.cbl */
      cob_set_location (st_1, 202, NULL, st_23, st_3);
      /* PERFORM FORMAT-PAREN-SPACE-PROCEDURE */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 20;
      frame_ptr->return_address_ptr = &&l_35;
      goto l_20;
      l_35:
      frame_ptr--;
      goto l_12;
    }

    /* End EVALUATE */
    l_12:;
    cob_add_int (&f_25, 1, 0);
  }

  /* Line: 210       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 210, NULL, st_23, st_6);
  memcpy (b_44, "ADD  ", 5);

  /* Line: 211       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 211, NULL, st_23, st_6);
  memcpy (b_45, "TOKENIZER:FORMAT-LISP-PROCEDURE         ", 40);

  /* Line: 213       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 213, NULL, st_23, st_6);
  cob_move ((cob_field *)&c_5, &f_47);

  /* Line: 215       : CALL               : tokenizer.cbl */
  cob_set_location (st_1, 215, NULL, st_23, st_18);
  cob_procedure_params[0] = &f_44;
  cob_procedure_params[1] = &f_45;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_LOGGER.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
    call_LOGGER.funcvoid = cob_resolve_cobol ("LOGGER", 0, 1);
  }
  b_1 = ((int (*)(void *, void *))call_LOGGER.funcint) (b_44, b_45);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 216       : Paragraph CALC-LISP-LENGTH        : tokenizer.cbl */
  l_13:;

  /* Line: 218       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 218, NULL, st_25, st_6);
  memset (b_12, 48, 10);

  /* Line: 219       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 219, NULL, st_25, st_6);
  memset (b_16, 48, 10);

  /* Line: 220       : SET                : tokenizer.cbl */
  cob_set_location (st_1, 220, NULL, st_25, st_8);
  *(b_14) = 78;

  /* Line: 221       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 221, NULL, st_25, st_3);
  memcpy (b_25, "0000000001", 10);
  for (;;)
  {
    if (((int)cob_cmp_numdisp (b_25, 10, 200LL, 0) == 0))
      break;

    /* Line: 223       : IF                 : tokenizer.cbl */
    cob_set_location (st_1, 223, NULL, st_25, st_9);
    if (((int)(int)(*(b_13 + (cob_get_int (&f_25) - 1)) - 59) == 0))
    {

      /* Line: 225       : SET                : tokenizer.cbl */
      cob_set_location (st_1, 225, NULL, st_25, st_8);
      *(b_14) = 89;
    }
    else
    {
      /* ELSE */

      /* Line: 226       : IF                 : tokenizer.cbl */
      cob_set_location (st_1, 226, NULL, st_25, st_9);
      if (!((int)(int)(*(b_13 + (cob_get_int (&f_25) - 1)) - 32) == 0))
      {

        /* Line: 228       : ADD                : tokenizer.cbl */
        cob_set_location (st_1, 228, NULL, st_25, st_10);
        cob_add_int (&f_12, 1, 0);

        /* Line: 229       : ADD                : tokenizer.cbl */
        cob_set_location (st_1, 229, NULL, st_25, st_10);
        cob_add (&f_12, &f_17, 0);

        /* Line: 230       : MOVE               : tokenizer.cbl */
        cob_set_location (st_1, 230, NULL, st_25, st_6);
        memset (b_16, 48, 10);
      }
      else
      {
        /* ELSE */

        /* Line: 232       : ADD                : tokenizer.cbl */
        cob_set_location (st_1, 232, NULL, st_25, st_10);
        cob_add_int (&f_17, 1, 0);
      }
    }
    cob_add_int (&f_25, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 13)
    goto *frame_ptr->return_address_ptr;

  /* Line: 235       : Paragraph RESET-PARSE-FLAGS-PROCEDURE: tokenizer.cbl */

  /* Line: 236       : SET                : tokenizer.cbl */
  cob_set_location (st_1, 236, NULL, st_26, st_8);
  *(b_31) = 78;

  /* Line: 237       : SET                : tokenizer.cbl */
  cob_set_location (st_1, 237, NULL, st_26, st_8);
  *(b_31 + 1) = 78;

  /* Line: 238       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 238, NULL, st_26, st_6);
  memset (b_36 + 7, 48, 5);

  /* Line: 239       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 239, NULL, st_26, st_6);
  memset (b_36 + 12, 48, 5);

  /* Line: 240       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 240, NULL, st_26, st_6);
  memset (b_36 + 17, 48, 5);

  /* Line: 241       : Paragraph PRINT-PARSE-FLAGS-PROCEDURE: tokenizer.cbl */

  /* Line: 242       : DISPLAY            : tokenizer.cbl */
  cob_set_location (st_1, 242, NULL, st_27, st_22);
  cob_display (0, 1, 2, &c_6, &f_32);

  /* Line: 243       : DISPLAY            : tokenizer.cbl */
  cob_set_location (st_1, 243, NULL, st_27, st_22);
  cob_display (0, 1, 2, &c_7, &f_34);

  /* Line: 244       : DISPLAY            : tokenizer.cbl */
  cob_set_location (st_1, 244, NULL, st_27, st_22);
  cob_display (0, 1, 2, &c_8, &f_41);

  /* Line: 245       : DISPLAY            : tokenizer.cbl */
  cob_set_location (st_1, 245, NULL, st_27, st_22);
  cob_display (0, 1, 2, &c_9, &f_42);

  /* Line: 246       : DISPLAY            : tokenizer.cbl */
  cob_set_location (st_1, 246, NULL, st_27, st_22);
  cob_display (0, 1, 2, &c_10, &f_43);

  /* Line: 247       : Paragraph FORMAT-CHECK-PAREN-PROCEDURE: tokenizer.cbl */
  l_16:;

  /* Line: 249       : SUBTRACT           : tokenizer.cbl */
  cob_set_location (st_1, 249, NULL, st_28, st_13);
  cob_sub_int (&f_25, 1, 0);

  /* Line: 250       : IF                 : tokenizer.cbl */
  cob_set_location (st_1, 250, NULL, st_28, st_9);
  if (!((int)(int)(*(b_9 + (cob_get_int (&f_25) - 1)) - 32) == 0))
  {

    /* Line: 251       : SET                : tokenizer.cbl */
    cob_set_location (st_1, 251, NULL, st_28, st_8);
    *(b_16 + 11) = 89;
  }

  /* Line: 254       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 254, NULL, st_28, st_10);
  cob_add_int (&f_25, 2, 0);

  /* Line: 255       : IF                 : tokenizer.cbl */
  cob_set_location (st_1, 255, NULL, st_28, st_9);
  if (!((int)(int)(*(b_9 + (cob_get_int (&f_25) - 1)) - 32) == 0))
  {

    /* Line: 256       : SET                : tokenizer.cbl */
    cob_set_location (st_1, 256, NULL, st_28, st_8);
    *(b_16 + 10) = 89;
  }

  /* Line: 259       : SUBTRACT           : tokenizer.cbl */
  cob_set_location (st_1, 259, NULL, st_28, st_13);
  cob_sub_int (&f_25, 1, 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Line: 261       : Paragraph FORMAT-ADD-LEFT-SPACE   : tokenizer.cbl */
  l_17:;

  /* Line: 262       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 262, NULL, st_29, st_6);
  memcpy (b_16 + 2012, b_25, 10);

  /* Line: 263       : SUBTRACT           : tokenizer.cbl */
  cob_set_location (st_1, 263, NULL, st_29, st_13);
  cob_sub_int (&f_23, 1, 0);

  /* Line: 264       : STRING             : tokenizer.cbl */
  cob_set_location (st_1, 264, NULL, st_29, st_12);
  cob_string_init (&f_9, NULL);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_23), b_16 + 12 + 0, &a_4));
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_2);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_12), b_16 + 12 + (cob_get_int (&f_25) - 1), &a_4));
  cob_string_finish ();

  /* Line: 269       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 269, NULL, st_29, st_10);
  cob_add_int (&f_25, 1, 0);

  /* Line: 270       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 270, NULL, st_29, st_10);
  cob_add_int (&f_12, 1, 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address_ptr;

  /* Line: 271       : Paragraph FORMAT-ADD-RIGHT-SPACE  : tokenizer.cbl */
  l_18:;

  /* Line: 272       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 272, NULL, st_30, st_6);
  memcpy (b_16 + 2012, b_25, 10);

  /* Line: 273       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 273, NULL, st_30, st_10);
  cob_add_int (&f_23, 1, 0);

  /* Line: 274       : STRING             : tokenizer.cbl */
  cob_set_location (st_1, 274, NULL, st_30, st_12);
  cob_string_init (&f_9, NULL);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_25), b_16 + 12 + 0, &a_4));
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_2);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_12), b_16 + 12 + (cob_get_int (&f_23) - 1), &a_4));
  cob_string_finish ();

  /* Line: 279       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 279, NULL, st_30, st_10);
  cob_add_int (&f_25, 1, 0);

  /* Line: 280       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 280, NULL, st_30, st_10);
  cob_add_int (&f_12, 1, 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 18)
    goto *frame_ptr->return_address_ptr;

  /* Line: 281       : Paragraph FORMAT-ADD-BOTH-SPACES  : tokenizer.cbl */
  l_19:;

  /* Line: 282       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 282, NULL, st_31, st_6);
  memcpy (b_16 + 2012, b_25, 10);

  /* Line: 283       : SUBTRACT           : tokenizer.cbl */
  cob_set_location (st_1, 283, NULL, st_31, st_13);
  cob_sub_int (&f_23, 1, 0);

  /* Line: 284       : MOVE               : tokenizer.cbl */
  cob_set_location (st_1, 284, NULL, st_31, st_6);
  *(b_16 + 2022) = *(b_16 + 12 + (cob_get_int (&f_25) - 1));

  /* Line: 286       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 286, NULL, st_31, st_10);
  cob_add_int (&f_25, 1, 0);

  /* Line: 287       : STRING             : tokenizer.cbl */
  cob_set_location (st_1, 287, NULL, st_31, st_12);
  cob_string_init (&f_9, NULL);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_23), b_16 + 12 + 0, &a_4));
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_2);
  cob_string_delimited (NULL);
  cob_string_append (&f_24);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_2);
  cob_string_delimited (NULL);
  cob_string_append (COB_SET_FLD(f0, cob_get_int (&f_12), b_16 + 12 + (cob_get_int (&f_25) - 1), &a_4));
  cob_string_finish ();

  /* Line: 294       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 294, NULL, st_31, st_10);
  cob_add_int (&f_25, 1, 0);

  /* Line: 295       : ADD                : tokenizer.cbl */
  cob_set_location (st_1, 295, NULL, st_31, st_10);
  cob_add_int (&f_12, 2, 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address_ptr;

  /* Line: 296       : Paragraph FORMAT-PAREN-SPACE-PROCEDURE: tokenizer.cbl */
  l_20:;

  /* Line: 297       : PERFORM            : tokenizer.cbl */
  cob_set_location (st_1, 297, NULL, st_32, st_3);
  /* PERFORM FORMAT-CHECK-PAREN-PROCEDURE */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_36;
  goto l_16;
  l_36:
  frame_ptr--;

  /* Line: 298       : IF                 : tokenizer.cbl */
  cob_set_location (st_1, 298, NULL, st_32, st_9);
  if ((((int)(int)(*(b_16 + 10) - 89) == 0) && 
      ((int)(int)(*(b_16 + 11) - 89) == 0)))
  {

    /* Line: 299       : PERFORM            : tokenizer.cbl */
    cob_set_location (st_1, 299, NULL, st_32, st_3);
    /* PERFORM FORMAT-ADD-BOTH-SPACES */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 19;
    frame_ptr->return_address_ptr = &&l_37;
    goto l_19;
    l_37:
    frame_ptr--;
  }
  else
  {
    /* ELSE */

    /* Line: 300       : IF                 : tokenizer.cbl */
    cob_set_location (st_1, 300, NULL, st_32, st_9);
    if (((int)(int)(*(b_16 + 10) - 89) == 0))
    {

      /* Line: 301       : PERFORM            : tokenizer.cbl */
      cob_set_location (st_1, 301, NULL, st_32, st_3);
      /* PERFORM FORMAT-ADD-RIGHT-SPACE */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
          cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 18;
      frame_ptr->return_address_ptr = &&l_38;
      goto l_18;
      l_38:
      frame_ptr--;
    }
    else
    {
      /* ELSE */

      /* Line: 302       : IF                 : tokenizer.cbl */
      cob_set_location (st_1, 302, NULL, st_32, st_9);
      if (((int)(int)(*(b_16 + 11) - 89) == 0))
      {

        /* Line: 303       : PERFORM            : tokenizer.cbl */
        cob_set_location (st_1, 303, NULL, st_32, st_3);
        /* PERFORM FORMAT-ADD-LEFT-SPACE */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
            cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 17;
        frame_ptr->return_address_ptr = &&l_39;
        goto l_17;
        l_39:
        frame_ptr--;
      }
    }
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 20)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;


  /* Paragraph Default Error Handler   */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  /* Initialize module structure */
  module->module_name = "TOKENIZER";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())TOKENIZER;
  module->module_cancel.funcptr = (void *(*)())TOKENIZER_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 3;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memset (b_8, 32, 100);
  memset (b_9, 32, 200);
  *(cob_u8_ptr)(b_10) = 32;
  memset (b_12, 48, 10);
  memset (b_13, 32, 200);
  *(cob_u8_ptr)(b_14) = 32;
  memset (b_16, 48, 10);
  memset (b_16 + 10, 32, 2002);
  memset (b_16 + 2012, 48, 10);
  *(cob_u8_ptr)(b_16 + 2022) = 32;
  memset (b_25, 48, 10);
  memset (b_26, 48, 10);
  memset (b_27, 48, 10);
  memset (b_28, 48, 10);
  *(cob_u8_ptr)(b_29) = 32;
  memset (b_31, 32, 2);
  memset (b_36, 48, 5);
  memset (b_36 + 5, 32, 2);
  memset (b_36 + 7, 48, 15);
  memset (b_44, 32, 5);
  memset (b_45, 32, 140);


  if (!h_LISP_FILE)
  {
    h_LISP_FILE = cob_cache_malloc (sizeof(cob_file));
  }
  h_LISP_FILE->select_name = (const char *)"LISP-FILE";
  h_LISP_FILE->file_status = h_LISP_FILE_status;
  memset (h_LISP_FILE_status, '0', 2);
  h_LISP_FILE->assign = &f_8;
  h_LISP_FILE->record = &f_7;
  h_LISP_FILE->variable_record = NULL;
  h_LISP_FILE->record_min = 0;
  h_LISP_FILE->record_max = 200;
  h_LISP_FILE->nkeys = 0;
  h_LISP_FILE->keys = NULL;
  h_LISP_FILE->file = NULL;
  h_LISP_FILE->fd = -1;
  h_LISP_FILE->organization = 1;
  h_LISP_FILE->access_mode = 1;
  h_LISP_FILE->lock_mode = 0;
  h_LISP_FILE->open_mode = 0;
  h_LISP_FILE->flag_optional = 0;
  h_LISP_FILE->last_open_mode = 0;
  h_LISP_FILE->flag_operation = 0;
  h_LISP_FILE->flag_nonexistent = 0;
  h_LISP_FILE->flag_end_of_file = 0;
  h_LISP_FILE->flag_begin_of_file = 0;
  h_LISP_FILE->flag_first_read = 0;
  h_LISP_FILE->flag_read_done = 0;
  h_LISP_FILE->flag_select_features = 0;
  h_LISP_FILE->flag_needs_nl = 0;
  h_LISP_FILE->flag_needs_top = 0;
  h_LISP_FILE->file_version = 1;

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  cob_close (h_LISP_FILE, NULL, COB_CLOSE_NORMAL, 1);
  cob_cache_free (h_LISP_FILE);
  h_LISP_FILE = NULL;
  call_LOGGER.funcvoid = NULL;
  b_1 = 0;
  cob_cache_free (module);
  module = NULL;

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'TOKENIZER' */

/* End functions */

